// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type BootstrapProfileInput struct {
	Username   string  `json:"username"`
	Email      *string `json:"email,omitempty"`
	FullName   string  `json:"fullName"`
	Discipline *string `json:"discipline,omitempty"`
	University *string `json:"university,omitempty"`
}

type CreateProjectInput struct {
	Title       string   `json:"title"`
	Description string   `json:"description"`
	Constraints *string  `json:"constraints,omitempty"`
	Disciplines []string `json:"disciplines"`
	TeamSizeMin *int     `json:"teamSizeMin,omitempty"`
	TeamSizeMax *int     `json:"teamSizeMax,omitempty"`
	FileURL     *string  `json:"fileUrl,omitempty"`
	VideoURL    *string  `json:"videoUrl,omitempty"`
}

type CreateTeamInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Discipline  *string `json:"discipline,omitempty"`
	MaxSize     *int    `json:"maxSize,omitempty"`
}

type Message struct {
	ID        string `json:"id"`
	Sender    *User  `json:"sender"`
	Receiver  *User  `json:"receiver"`
	Body      string `json:"body"`
	Read      bool   `json:"read"`
	CreatedAt string `json:"createdAt"`
}

type Mutation struct {
}

type Notification struct {
	ID        string `json:"id"`
	Type      string `json:"type"`
	Payload   string `json:"payload"`
	Read      bool   `json:"read"`
	CreatedAt string `json:"createdAt"`
}

type Project struct {
	ID           string                `json:"id"`
	Title        string                `json:"title"`
	Description  string                `json:"description"`
	Constraints  *string               `json:"constraints,omitempty"`
	Disciplines  []string              `json:"disciplines"`
	TeamSizeMin  int                   `json:"teamSizeMin"`
	TeamSizeMax  int                   `json:"teamSizeMax"`
	Status       ProjectStatus         `json:"status"`
	Owner        *User                 `json:"owner"`
	Team         *Team                 `json:"team,omitempty"`
	FileURL      *string               `json:"fileUrl,omitempty"`
	VideoURL     *string               `json:"videoUrl,omitempty"`
	Applications []*ProjectApplication `json:"applications"`
	CreatedAt    string                `json:"createdAt"`
}

type ProjectApplication struct {
	ID        string            `json:"id"`
	Project   *Project          `json:"project"`
	Team      *Team             `json:"team"`
	Message   *string           `json:"message,omitempty"`
	Status    ApplicationStatus `json:"status"`
	CreatedAt string            `json:"createdAt"`
}

type Query struct {
}

type SignUploadInput struct {
	Kind        UploadAssetKind `json:"kind"`
	Filename    string          `json:"filename"`
	ContentType string          `json:"contentType"`
	Size        int             `json:"size"`
}

type Tag struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	IsPredefined bool   `json:"isPredefined"`
}

type Team struct {
	ID          string            `json:"id"`
	Name        string            `json:"name"`
	Description *string           `json:"description,omitempty"`
	IsComplete  bool              `json:"isComplete"`
	MaxSize     int               `json:"maxSize"`
	Discipline  *string           `json:"discipline,omitempty"`
	Members     []*TeamMembership `json:"members"`
	Project     *Project          `json:"project,omitempty"`
	CreatedBy   *User             `json:"createdBy"`
	CreatedAt   string            `json:"createdAt"`
}

type TeamJoinRequest struct {
	ID        string            `json:"id"`
	Team      *Team             `json:"team"`
	User      *User             `json:"user"`
	Message   *string           `json:"message,omitempty"`
	Status    ApplicationStatus `json:"status"`
	CreatedAt string            `json:"createdAt"`
}

type TeamMembership struct {
	ID       string   `json:"id"`
	User     *User    `json:"user"`
	Team     *Team    `json:"team"`
	Role     TeamRole `json:"role"`
	JoinedAt string   `json:"joinedAt"`
}

type UpdateProfileInput struct {
	FullName     string  `json:"fullName"`
	Bio          *string `json:"bio,omitempty"`
	Discipline   *string `json:"discipline,omitempty"`
	University   *string `json:"university,omitempty"`
	LinkedinURL  *string `json:"linkedinUrl,omitempty"`
	GithubURL    *string `json:"githubUrl,omitempty"`
	PortfolioURL *string `json:"portfolioUrl,omitempty"`
	ResumeURL    *string `json:"resumeUrl,omitempty"`
	AvatarURL    *string `json:"avatarUrl,omitempty"`
}

type UpdateProjectInput struct {
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Constraints *string       `json:"constraints,omitempty"`
	Disciplines []string      `json:"disciplines"`
	TeamSizeMin int           `json:"teamSizeMin"`
	TeamSizeMax int           `json:"teamSizeMax"`
	Status      ProjectStatus `json:"status"`
	FileURL     *string       `json:"fileUrl,omitempty"`
	VideoURL    *string       `json:"videoUrl,omitempty"`
}

type UpdateTeamInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Discipline  *string `json:"discipline,omitempty"`
	MaxSize     int     `json:"maxSize"`
	IsComplete  bool    `json:"isComplete"`
}

type UploadField struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type UploadSignature struct {
	URL       string         `json:"url"`
	Key       string         `json:"key"`
	PublicURL *string        `json:"publicUrl,omitempty"`
	ExpiresAt string         `json:"expiresAt"`
	Fields    []*UploadField `json:"fields"`
}

type User struct {
	ID           string  `json:"id"`
	AuthUserID   string  `json:"authUserId"`
	Username     string  `json:"username"`
	Email        *string `json:"email,omitempty"`
	FullName     string  `json:"fullName"`
	Bio          *string `json:"bio,omitempty"`
	Discipline   *string `json:"discipline,omitempty"`
	University   *string `json:"university,omitempty"`
	LinkedinURL  *string `json:"linkedinUrl,omitempty"`
	GithubURL    *string `json:"githubUrl,omitempty"`
	PortfolioURL *string `json:"portfolioUrl,omitempty"`
	ResumeURL    *string `json:"resumeUrl,omitempty"`
	AvatarURL    *string `json:"avatarUrl,omitempty"`
	Tags         []*Tag  `json:"tags"`
	CreatedAt    string  `json:"createdAt"`
}

type ApplicationStatus string

const (
	ApplicationStatusPending  ApplicationStatus = "PENDING"
	ApplicationStatusAccepted ApplicationStatus = "ACCEPTED"
	ApplicationStatusRejected ApplicationStatus = "REJECTED"
)

var AllApplicationStatus = []ApplicationStatus{
	ApplicationStatusPending,
	ApplicationStatusAccepted,
	ApplicationStatusRejected,
}

func (e ApplicationStatus) IsValid() bool {
	switch e {
	case ApplicationStatusPending, ApplicationStatusAccepted, ApplicationStatusRejected:
		return true
	}
	return false
}

func (e ApplicationStatus) String() string {
	return string(e)
}

func (e *ApplicationStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ApplicationStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ApplicationStatus", str)
	}
	return nil
}

func (e ApplicationStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ApplicationStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ApplicationStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ProjectStatus string

const (
	ProjectStatusOpen     ProjectStatus = "OPEN"
	ProjectStatusInReview ProjectStatus = "IN_REVIEW"
	ProjectStatusClaimed  ProjectStatus = "CLAIMED"
	ProjectStatusClosed   ProjectStatus = "CLOSED"
)

var AllProjectStatus = []ProjectStatus{
	ProjectStatusOpen,
	ProjectStatusInReview,
	ProjectStatusClaimed,
	ProjectStatusClosed,
}

func (e ProjectStatus) IsValid() bool {
	switch e {
	case ProjectStatusOpen, ProjectStatusInReview, ProjectStatusClaimed, ProjectStatusClosed:
		return true
	}
	return false
}

func (e ProjectStatus) String() string {
	return string(e)
}

func (e *ProjectStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProjectStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProjectStatus", str)
	}
	return nil
}

func (e ProjectStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProjectStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProjectStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TeamRole string

const (
	TeamRoleLead   TeamRole = "LEAD"
	TeamRoleCoLead TeamRole = "CO_LEAD"
	TeamRoleMember TeamRole = "MEMBER"
)

var AllTeamRole = []TeamRole{
	TeamRoleLead,
	TeamRoleCoLead,
	TeamRoleMember,
}

func (e TeamRole) IsValid() bool {
	switch e {
	case TeamRoleLead, TeamRoleCoLead, TeamRoleMember:
		return true
	}
	return false
}

func (e TeamRole) String() string {
	return string(e)
}

func (e *TeamRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TeamRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TeamRole", str)
	}
	return nil
}

func (e TeamRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TeamRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TeamRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UploadAssetKind string

const (
	UploadAssetKindResume      UploadAssetKind = "RESUME"
	UploadAssetKindProjectFile UploadAssetKind = "PROJECT_FILE"
	UploadAssetKindAvatar      UploadAssetKind = "AVATAR"
	UploadAssetKindVideo       UploadAssetKind = "VIDEO"
)

var AllUploadAssetKind = []UploadAssetKind{
	UploadAssetKindResume,
	UploadAssetKindProjectFile,
	UploadAssetKindAvatar,
	UploadAssetKindVideo,
}

func (e UploadAssetKind) IsValid() bool {
	switch e {
	case UploadAssetKindResume, UploadAssetKindProjectFile, UploadAssetKindAvatar, UploadAssetKindVideo:
		return true
	}
	return false
}

func (e UploadAssetKind) String() string {
	return string(e)
}

func (e *UploadAssetKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UploadAssetKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UploadAssetKind", str)
	}
	return nil
}

func (e UploadAssetKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UploadAssetKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UploadAssetKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
