// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deactivateAccountState = `-- name: DeactivateAccountState :execrows
UPDATE app.account_states
SET status = 'DEACTIVATED',
    state_version = state_version + 1,
    session_revocation_version = session_revocation_version + 1,
    deactivated_at = now(),
    updated_at = now()
WHERE user_id = $1
  AND status = 'ACTIVE'
`

func (q *Queries) DeactivateAccountState(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateAccountState, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdentityRealmByKey = `-- name: GetIdentityRealmByKey :one
SELECT id, realm_key, auth_system, issuer, created_at, updated_at
FROM app.identity_realms
WHERE realm_key = $1
`

func (q *Queries) GetIdentityRealmByKey(ctx context.Context, realmKey string) (AppIdentityRealm, error) {
	row := q.db.QueryRow(ctx, getIdentityRealmByKey, realmKey)
	var i AppIdentityRealm
	err := row.Scan(
		&i.ID,
		&i.RealmKey,
		&i.AuthSystem,
		&i.Issuer,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserIdentityByRealmSubject = `-- name: GetUserIdentityByRealmSubject :one
SELECT identity.id, identity.user_id, identity.realm_id, identity.identity_subject, identity.verified_email, identity.email_verified_at, identity.auth_version, identity.sync_status, identity.linked_at, identity.last_seen_at, identity.last_synced_at, identity.reconcile_after, identity.unlinked_at, identity.created_at, identity.updated_at
FROM app.user_identities AS identity
JOIN app.identity_realms AS realm ON realm.id = identity.realm_id
WHERE realm.realm_key = $1
  AND identity.identity_subject = $2
  AND identity.unlinked_at IS NULL
`

type GetUserIdentityByRealmSubjectParams struct {
	RealmKey        string `json:"realm_key"`
	IdentitySubject string `json:"identity_subject"`
}

func (q *Queries) GetUserIdentityByRealmSubject(ctx context.Context, arg GetUserIdentityByRealmSubjectParams) (AppUserIdentity, error) {
	row := q.db.QueryRow(ctx, getUserIdentityByRealmSubject, arg.RealmKey, arg.IdentitySubject)
	var i AppUserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RealmID,
		&i.IdentitySubject,
		&i.VerifiedEmail,
		&i.EmailVerifiedAt,
		&i.AuthVersion,
		&i.SyncStatus,
		&i.LinkedAt,
		&i.LastSeenAt,
		&i.LastSyncedAt,
		&i.ReconcileAfter,
		&i.UnlinkedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getViewerBootstrapByRealmSubject = `-- name: GetViewerBootstrapByRealmSubject :one
SELECT
  product_user.id::text AS product_user_id,
  account.status AS account_state,
  identity.sync_status,
  CASE WHEN product_user.profile_complete THEN 'COMPLETE' ELSE 'NOT_STARTED' END::text AS onboarding_state,
  (CASE WHEN product_user.username LIKE 'user_%' THEN '' ELSE product_user.username END)::text AS username,
  (CASE WHEN product_user.full_name = 'New user' THEN '' ELSE product_user.full_name END)::text AS display_name,
  COALESCE(
    array_agg(grant_record.role ORDER BY grant_record.role)
      FILTER (
        WHERE grant_record.source = 'SELF_SERVICE'
          AND grant_record.revoked_at IS NULL
          AND grant_record.role IN ('STUDENT', 'SPONSOR')
      ),
    ARRAY[]::text[]
  )::text[] AS self_service_roles
FROM app.user_identities AS identity
JOIN app.identity_realms AS realm ON realm.id = identity.realm_id
JOIN public.users AS product_user ON product_user.id = identity.user_id
JOIN app.account_states AS account ON account.user_id = product_user.id
LEFT JOIN app.role_grants AS grant_record ON grant_record.user_id = product_user.id
WHERE realm.realm_key = $1
  AND identity.identity_subject = $2
  AND identity.unlinked_at IS NULL
GROUP BY product_user.id, account.status, identity.sync_status
`

type GetViewerBootstrapByRealmSubjectParams struct {
	RealmKey        string `json:"realm_key"`
	IdentitySubject string `json:"identity_subject"`
}

type GetViewerBootstrapByRealmSubjectRow struct {
	ProductUserID    string   `json:"product_user_id"`
	AccountState     string   `json:"account_state"`
	SyncStatus       string   `json:"sync_status"`
	OnboardingState  string   `json:"onboarding_state"`
	Username         string   `json:"username"`
	DisplayName      string   `json:"display_name"`
	SelfServiceRoles []string `json:"self_service_roles"`
}

func (q *Queries) GetViewerBootstrapByRealmSubject(ctx context.Context, arg GetViewerBootstrapByRealmSubjectParams) (GetViewerBootstrapByRealmSubjectRow, error) {
	row := q.db.QueryRow(ctx, getViewerBootstrapByRealmSubject, arg.RealmKey, arg.IdentitySubject)
	var i GetViewerBootstrapByRealmSubjectRow
	err := row.Scan(
		&i.ProductUserID,
		&i.AccountState,
		&i.SyncStatus,
		&i.OnboardingState,
		&i.Username,
		&i.DisplayName,
		&i.SelfServiceRoles,
	)
	return i, err
}

const listActiveRoleGrantsForUser = `-- name: ListActiveRoleGrantsForUser :many
SELECT grant_record.id, grant_record.user_id, grant_record.role, grant_record.source, grant_record.granted_by, grant_record.granted_at, grant_record.revoked_by, grant_record.revoked_at, grant_record.reason, grant_record.created_at, grant_record.updated_at
FROM app.role_grants AS grant_record
WHERE grant_record.user_id = $1
  AND grant_record.revoked_at IS NULL
ORDER BY grant_record.granted_at, grant_record.id
`

func (q *Queries) ListActiveRoleGrantsForUser(ctx context.Context, userID pgtype.UUID) ([]AppRoleGrant, error) {
	rows, err := q.db.Query(ctx, listActiveRoleGrantsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppRoleGrant
	for rows.Next() {
		var i AppRoleGrant
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.Source,
			&i.GrantedBy,
			&i.GrantedAt,
			&i.RevokedBy,
			&i.RevokedAt,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
