// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminUser struct {
	UserID    pgtype.UUID        `json:"user_id"`
	GrantedAt pgtype.Timestamptz `json:"granted_at"`
}

type Message struct {
	ID         pgtype.UUID        `json:"id"`
	SenderID   pgtype.UUID        `json:"sender_id"`
	ReceiverID pgtype.UUID        `json:"receiver_id"`
	Body       string             `json:"body"`
	Read       bool               `json:"read"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Type      string             `json:"type"`
	Payload   []byte             `json:"payload"`
	Read      bool               `json:"read"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Constraints pgtype.Text        `json:"constraints"`
	Disciplines []string           `json:"disciplines"`
	TeamSizeMin int32              `json:"team_size_min"`
	TeamSizeMax int32              `json:"team_size_max"`
	Status      string             `json:"status"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	TeamID      pgtype.UUID        `json:"team_id"`
	FileUrl     pgtype.Text        `json:"file_url"`
	VideoUrl    pgtype.Text        `json:"video_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ProjectApplication struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	TeamID    pgtype.UUID        `json:"team_id"`
	Message   pgtype.Text        `json:"message"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Tag struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	IsPredefined bool        `json:"is_predefined"`
}

type Team struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsComplete  bool               `json:"is_complete"`
	MaxSize     int32              `json:"max_size"`
	Discipline  pgtype.Text        `json:"discipline"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TeamJoinRequest struct {
	ID        pgtype.UUID        `json:"id"`
	TeamID    pgtype.UUID        `json:"team_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Message   pgtype.Text        `json:"message"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TeamMembership struct {
	ID       pgtype.UUID        `json:"id"`
	TeamID   pgtype.UUID        `json:"team_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	Role     string             `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	AuthUserID   string             `json:"auth_user_id"`
	Username     string             `json:"username"`
	Email        pgtype.Text        `json:"email"`
	FullName     string             `json:"full_name"`
	Bio          pgtype.Text        `json:"bio"`
	Discipline   pgtype.Text        `json:"discipline"`
	University   pgtype.Text        `json:"university"`
	LinkedinUrl  pgtype.Text        `json:"linkedin_url"`
	GithubUrl    pgtype.Text        `json:"github_url"`
	PortfolioUrl pgtype.Text        `json:"portfolio_url"`
	ResumeUrl    pgtype.Text        `json:"resume_url"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserTag struct {
	UserID pgtype.UUID `json:"user_id"`
	TagID  pgtype.UUID `json:"tag_id"`
}
