// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyToProject = `-- name: ApplyToProject :one
INSERT INTO project_applications (project_id, team_id, message)
VALUES ($1, $2, $3)
RETURNING id, project_id, team_id, message, status, created_at
`

type ApplyToProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	TeamID    pgtype.UUID `json:"team_id"`
	Message   pgtype.Text `json:"message"`
}

func (q *Queries) ApplyToProject(ctx context.Context, arg ApplyToProjectParams) (ProjectApplication, error) {
	row := q.db.QueryRow(ctx, applyToProject, arg.ProjectID, arg.TeamID, arg.Message)
	var i ProjectApplication
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TeamID,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const associateProject = `-- name: AssociateProject :one
UPDATE teams
SET project_id = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, is_complete, max_size, discipline, created_by, project_id, created_at, updated_at
`

type AssociateProjectParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) AssociateProject(ctx context.Context, arg AssociateProjectParams) (Team, error) {
	row := q.db.QueryRow(ctx, associateProject, arg.ID, arg.ProjectID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsComplete,
		&i.MaxSize,
		&i.Discipline,
		&i.CreatedBy,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimProject = `-- name: ClaimProject :one
UPDATE projects
SET team_id = $2,
    status = 'CLAIMED',
    updated_at = now()
WHERE id = $1
RETURNING id, title, description, constraints, disciplines, team_size_min, team_size_max, status, owner_id, team_id, file_url, video_url, created_at, updated_at
`

type ClaimProjectParams struct {
	ID     pgtype.UUID `json:"id"`
	TeamID pgtype.UUID `json:"team_id"`
}

func (q *Queries) ClaimProject(ctx context.Context, arg ClaimProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, claimProject, arg.ID, arg.TeamID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Constraints,
		&i.Disciplines,
		&i.TeamSizeMin,
		&i.TeamSizeMax,
		&i.Status,
		&i.OwnerID,
		&i.TeamID,
		&i.FileUrl,
		&i.VideoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (title, description, constraints, disciplines, team_size_min, team_size_max, owner_id, file_url, video_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, title, description, constraints, disciplines, team_size_min, team_size_max, status, owner_id, team_id, file_url, video_url, created_at, updated_at
`

type CreateProjectParams struct {
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Constraints pgtype.Text `json:"constraints"`
	Disciplines []string    `json:"disciplines"`
	TeamSizeMin int32       `json:"team_size_min"`
	TeamSizeMax int32       `json:"team_size_max"`
	OwnerID     pgtype.UUID `json:"owner_id"`
	FileUrl     pgtype.Text `json:"file_url"`
	VideoUrl    pgtype.Text `json:"video_url"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Title,
		arg.Description,
		arg.Constraints,
		arg.Disciplines,
		arg.TeamSizeMin,
		arg.TeamSizeMax,
		arg.OwnerID,
		arg.FileUrl,
		arg.VideoUrl,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Constraints,
		&i.Disciplines,
		&i.TeamSizeMin,
		&i.TeamSizeMax,
		&i.Status,
		&i.OwnerID,
		&i.TeamID,
		&i.FileUrl,
		&i.VideoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, title, description, constraints, disciplines, team_size_min, team_size_max, status, owner_id, team_id, file_url, video_url, created_at, updated_at FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Constraints,
		&i.Disciplines,
		&i.TeamSizeMin,
		&i.TeamSizeMax,
		&i.Status,
		&i.OwnerID,
		&i.TeamID,
		&i.FileUrl,
		&i.VideoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectApplication = `-- name: GetProjectApplication :one
SELECT id, project_id, team_id, message, status, created_at
FROM project_applications
WHERE id = $1
`

func (q *Queries) GetProjectApplication(ctx context.Context, id pgtype.UUID) (ProjectApplication, error) {
	row := q.db.QueryRow(ctx, getProjectApplication, id)
	var i ProjectApplication
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TeamID,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listProjectApplications = `-- name: ListProjectApplications :many
SELECT pa.id, pa.project_id, pa.team_id, pa.message, pa.status, pa.created_at, t.name AS team_name
FROM project_applications pa
JOIN teams t ON t.id = pa.team_id
WHERE pa.project_id = $1
ORDER BY pa.created_at DESC
`

type ListProjectApplicationsRow struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	TeamID    pgtype.UUID        `json:"team_id"`
	Message   pgtype.Text        `json:"message"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	TeamName  string             `json:"team_name"`
}

func (q *Queries) ListProjectApplications(ctx context.Context, projectID pgtype.UUID) ([]ListProjectApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listProjectApplications, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectApplicationsRow
	for rows.Next() {
		var i ListProjectApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TeamID,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, title, description, constraints, disciplines, team_size_min, team_size_max, status, owner_id, team_id, file_url, video_url, created_at, updated_at
FROM projects
WHERE ($1::text IS NULL OR $1::text = ANY(disciplines))
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::text IS NULL OR title ILIKE '%' || $3::text || '%')
ORDER BY created_at DESC
`

type ListProjectsParams struct {
	Discipline pgtype.Text `json:"discipline"`
	Status     pgtype.Text `json:"status"`
	Search     pgtype.Text `json:"search"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, arg.Discipline, arg.Status, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Constraints,
			&i.Disciplines,
			&i.TeamSizeMin,
			&i.TeamSizeMax,
			&i.Status,
			&i.OwnerID,
			&i.TeamID,
			&i.FileUrl,
			&i.VideoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const respondToApplication = `-- name: RespondToApplication :one
UPDATE project_applications
SET status = $2
WHERE id = $1
RETURNING id, project_id, team_id, message, status, created_at
`

type RespondToApplicationParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) RespondToApplication(ctx context.Context, arg RespondToApplicationParams) (ProjectApplication, error) {
	row := q.db.QueryRow(ctx, respondToApplication, arg.ID, arg.Status)
	var i ProjectApplication
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TeamID,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET title = $2,
    description = $3,
    constraints = $4,
    disciplines = $5,
    team_size_min = $6,
    team_size_max = $7,
    status = $8,
    file_url = $9,
    video_url = $10,
    updated_at = now()
WHERE id = $1
RETURNING id, title, description, constraints, disciplines, team_size_min, team_size_max, status, owner_id, team_id, file_url, video_url, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Constraints pgtype.Text `json:"constraints"`
	Disciplines []string    `json:"disciplines"`
	TeamSizeMin int32       `json:"team_size_min"`
	TeamSizeMax int32       `json:"team_size_max"`
	Status      string      `json:"status"`
	FileUrl     pgtype.Text `json:"file_url"`
	VideoUrl    pgtype.Text `json:"video_url"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Constraints,
		arg.Disciplines,
		arg.TeamSizeMin,
		arg.TeamSizeMax,
		arg.Status,
		arg.FileUrl,
		arg.VideoUrl,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Constraints,
		&i.Disciplines,
		&i.TeamSizeMin,
		&i.TeamSizeMax,
		&i.Status,
		&i.OwnerID,
		&i.TeamID,
		&i.FileUrl,
		&i.VideoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
