// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMembership, error)
	ApplyToProject(ctx context.Context, arg ApplyToProjectParams) (ProjectApplication, error)
	AssociateProject(ctx context.Context, arg AssociateProjectParams) (Team, error)
	ClaimProject(ctx context.Context, arg ClaimProjectParams) (Project, error)
	CreateJoinRequest(ctx context.Context, arg CreateJoinRequestParams) (TeamJoinRequest, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteProject(ctx context.Context, id pgtype.UUID) error
	DeleteTeam(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetJoinRequest(ctx context.Context, id pgtype.UUID) (TeamJoinRequest, error)
	GetMessage(ctx context.Context, id pgtype.UUID) (Message, error)
	GetNotification(ctx context.Context, id pgtype.UUID) (Notification, error)
	GetProject(ctx context.Context, id pgtype.UUID) (Project, error)
	GetProjectApplication(ctx context.Context, id pgtype.UUID) (ProjectApplication, error)
	GetTeam(ctx context.Context, id pgtype.UUID) (Team, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByAuthID(ctx context.Context, authUserID string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	IsAdmin(ctx context.Context, userID pgtype.UUID) (bool, error)
	ListAdminUsers(ctx context.Context) ([]User, error)
	ListInboxUsers(ctx context.Context, senderID pgtype.UUID) ([]User, error)
	ListJoinRequestsForTeam(ctx context.Context, teamID pgtype.UUID) ([]ListJoinRequestsForTeamRow, error)
	ListMessagesWithUser(ctx context.Context, arg ListMessagesWithUserParams) ([]Message, error)
	ListNotifications(ctx context.Context, userID pgtype.UUID) ([]Notification, error)
	ListProjectApplications(ctx context.Context, projectID pgtype.UUID) ([]ListProjectApplicationsRow, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error)
	ListTeamMembers(ctx context.Context, teamID pgtype.UUID) ([]ListTeamMembersRow, error)
	ListTeams(ctx context.Context, arg ListTeamsParams) ([]Team, error)
	ListUserTags(ctx context.Context, userID pgtype.UUID) ([]Tag, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	MarkMessageRead(ctx context.Context, id pgtype.UUID) (Message, error)
	MarkNotificationRead(ctx context.Context, id pgtype.UUID) (Notification, error)
	PromoteTeamMember(ctx context.Context, arg PromoteTeamMemberParams) (TeamMembership, error)
	RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error
	RespondToApplication(ctx context.Context, arg RespondToApplicationParams) (ProjectApplication, error)
	RespondToJoinRequest(ctx context.Context, arg RespondToJoinRequestParams) (TeamJoinRequest, error)
	SendMessage(ctx context.Context, arg SendMessageParams) (Message, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (User, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error)
}

var _ Querier = (*Queries)(nil)
