// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: requests_messages_admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJoinRequest = `-- name: CreateJoinRequest :one
INSERT INTO team_join_requests (team_id, user_id, message)
VALUES ($1, $2, $3)
RETURNING id, team_id, user_id, message, status, created_at
`

type CreateJoinRequestParams struct {
	TeamID  pgtype.UUID `json:"team_id"`
	UserID  pgtype.UUID `json:"user_id"`
	Message pgtype.Text `json:"message"`
}

func (q *Queries) CreateJoinRequest(ctx context.Context, arg CreateJoinRequestParams) (TeamJoinRequest, error) {
	row := q.db.QueryRow(ctx, createJoinRequest, arg.TeamID, arg.UserID, arg.Message)
	var i TeamJoinRequest
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getJoinRequest = `-- name: GetJoinRequest :one
SELECT id, team_id, user_id, message, status, created_at
FROM team_join_requests
WHERE id = $1
`

func (q *Queries) GetJoinRequest(ctx context.Context, id pgtype.UUID) (TeamJoinRequest, error) {
	row := q.db.QueryRow(ctx, getJoinRequest, id)
	var i TeamJoinRequest
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, sender_id, receiver_id, body, read, created_at
FROM messages
WHERE id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id pgtype.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Body,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const getNotification = `-- name: GetNotification :one
SELECT id, user_id, type, payload, read, created_at
FROM notifications
WHERE id = $1
`

func (q *Queries) GetNotification(ctx context.Context, id pgtype.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Payload,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const isAdmin = `-- name: IsAdmin :one
SELECT EXISTS(SELECT 1 FROM admin_users WHERE user_id = $1)
`

func (q *Queries) IsAdmin(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isAdmin, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT u.id, u.auth_user_id, u.username, u.email, u.full_name, u.bio, u.discipline, u.university, u.linkedin_url, u.github_url, u.portfolio_url, u.resume_url, u.avatar_url, u.created_at, u.updated_at
FROM users u
JOIN admin_users au ON au.user_id = u.id
ORDER BY au.granted_at DESC
`

func (q *Queries) ListAdminUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.AuthUserID,
			&i.Username,
			&i.Email,
			&i.FullName,
			&i.Bio,
			&i.Discipline,
			&i.University,
			&i.LinkedinUrl,
			&i.GithubUrl,
			&i.PortfolioUrl,
			&i.ResumeUrl,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInboxUsers = `-- name: ListInboxUsers :many
SELECT DISTINCT u.id, u.auth_user_id, u.username, u.email, u.full_name, u.bio, u.discipline, u.university, u.linkedin_url, u.github_url, u.portfolio_url, u.resume_url, u.avatar_url, u.created_at, u.updated_at
FROM users u
JOIN messages m ON u.id = CASE WHEN m.sender_id = $1 THEN m.receiver_id ELSE m.sender_id END
WHERE m.sender_id = $1 OR m.receiver_id = $1
ORDER BY u.full_name
`

func (q *Queries) ListInboxUsers(ctx context.Context, senderID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listInboxUsers, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.AuthUserID,
			&i.Username,
			&i.Email,
			&i.FullName,
			&i.Bio,
			&i.Discipline,
			&i.University,
			&i.LinkedinUrl,
			&i.GithubUrl,
			&i.PortfolioUrl,
			&i.ResumeUrl,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJoinRequestsForTeam = `-- name: ListJoinRequestsForTeam :many
SELECT tjr.id, tjr.team_id, tjr.user_id, tjr.message, tjr.status, tjr.created_at, u.username, u.full_name
FROM team_join_requests tjr
JOIN users u ON u.id = tjr.user_id
WHERE tjr.team_id = $1
ORDER BY tjr.created_at DESC
`

type ListJoinRequestsForTeamRow struct {
	ID        pgtype.UUID        `json:"id"`
	TeamID    pgtype.UUID        `json:"team_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Message   pgtype.Text        `json:"message"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Username  string             `json:"username"`
	FullName  string             `json:"full_name"`
}

func (q *Queries) ListJoinRequestsForTeam(ctx context.Context, teamID pgtype.UUID) ([]ListJoinRequestsForTeamRow, error) {
	rows, err := q.db.Query(ctx, listJoinRequestsForTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJoinRequestsForTeamRow
	for rows.Next() {
		var i ListJoinRequestsForTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.Message,
			&i.Status,
			&i.CreatedAt,
			&i.Username,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesWithUser = `-- name: ListMessagesWithUser :many
SELECT id, sender_id, receiver_id, body, read, created_at
FROM messages
WHERE (sender_id = $1 AND receiver_id = $2)
   OR (sender_id = $2 AND receiver_id = $1)
ORDER BY created_at
`

type ListMessagesWithUserParams struct {
	SenderID   pgtype.UUID `json:"sender_id"`
	ReceiverID pgtype.UUID `json:"receiver_id"`
}

func (q *Queries) ListMessagesWithUser(ctx context.Context, arg ListMessagesWithUserParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesWithUser, arg.SenderID, arg.ReceiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.ReceiverID,
			&i.Body,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, type, payload, read, created_at
FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListNotifications(ctx context.Context, userID pgtype.UUID) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Payload,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessageRead = `-- name: MarkMessageRead :one
UPDATE messages
SET read = true
WHERE id = $1
RETURNING id, sender_id, receiver_id, body, read, created_at
`

func (q *Queries) MarkMessageRead(ctx context.Context, id pgtype.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, markMessageRead, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Body,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications
SET read = true
WHERE id = $1
RETURNING id, user_id, type, payload, read, created_at
`

func (q *Queries) MarkNotificationRead(ctx context.Context, id pgtype.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Payload,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const respondToJoinRequest = `-- name: RespondToJoinRequest :one
UPDATE team_join_requests
SET status = $2
WHERE id = $1
RETURNING id, team_id, user_id, message, status, created_at
`

type RespondToJoinRequestParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) RespondToJoinRequest(ctx context.Context, arg RespondToJoinRequestParams) (TeamJoinRequest, error) {
	row := q.db.QueryRow(ctx, respondToJoinRequest, arg.ID, arg.Status)
	var i TeamJoinRequest
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Message,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const sendMessage = `-- name: SendMessage :one
INSERT INTO messages (sender_id, receiver_id, body)
VALUES ($1, $2, $3)
RETURNING id, sender_id, receiver_id, body, read, created_at
`

type SendMessageParams struct {
	SenderID   pgtype.UUID `json:"sender_id"`
	ReceiverID pgtype.UUID `json:"receiver_id"`
	Body       string      `json:"body"`
}

func (q *Queries) SendMessage(ctx context.Context, arg SendMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, sendMessage, arg.SenderID, arg.ReceiverID, arg.Body)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Body,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}
