// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: teams.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTeamMember = `-- name: AddTeamMember :one
INSERT INTO team_memberships (team_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, team_id, user_id, role, joined_at
`

type AddTeamMemberParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, addTeamMember, arg.TeamID, arg.UserID, arg.Role)
	var i TeamMembership
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (name, description, discipline, max_size, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, is_complete, max_size, discipline, created_by, project_id, created_at, updated_at
`

type CreateTeamParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Discipline  pgtype.Text `json:"discipline"`
	MaxSize     int32       `json:"max_size"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.Name,
		arg.Description,
		arg.Discipline,
		arg.MaxSize,
		arg.CreatedBy,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsComplete,
		&i.MaxSize,
		&i.Discipline,
		&i.CreatedBy,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const getTeam = `-- name: GetTeam :one
SELECT id, name, description, is_complete, max_size, discipline, created_by, project_id, created_at, updated_at FROM teams WHERE id = $1
`

func (q *Queries) GetTeam(ctx context.Context, id pgtype.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsComplete,
		&i.MaxSize,
		&i.Discipline,
		&i.CreatedBy,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT tm.id, tm.team_id, tm.user_id, tm.role, tm.joined_at, u.username, u.full_name, u.discipline, u.university
FROM team_memberships tm
JOIN users u ON u.id = tm.user_id
WHERE tm.team_id = $1
ORDER BY tm.joined_at
`

type ListTeamMembersRow struct {
	ID         pgtype.UUID        `json:"id"`
	TeamID     pgtype.UUID        `json:"team_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Role       string             `json:"role"`
	JoinedAt   pgtype.Timestamptz `json:"joined_at"`
	Username   string             `json:"username"`
	FullName   string             `json:"full_name"`
	Discipline pgtype.Text        `json:"discipline"`
	University pgtype.Text        `json:"university"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, teamID pgtype.UUID) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMembersRow
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Username,
			&i.FullName,
			&i.Discipline,
			&i.University,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT id, name, description, is_complete, max_size, discipline, created_by, project_id, created_at, updated_at
FROM teams
WHERE ($1::text IS NULL OR discipline = $1::text)
  AND ($2::boolean IS NULL OR (project_id IS NOT NULL) = $2::boolean)
  AND ($3::boolean IS NULL OR is_complete = $3::boolean)
  AND ($4::text IS NULL OR name ILIKE '%' || $4::text || '%')
ORDER BY created_at DESC
`

type ListTeamsParams struct {
	Discipline pgtype.Text `json:"discipline"`
	HasProject pgtype.Bool `json:"has_project"`
	IsComplete pgtype.Bool `json:"is_complete"`
	Search     pgtype.Text `json:"search"`
}

func (q *Queries) ListTeams(ctx context.Context, arg ListTeamsParams) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeams,
		arg.Discipline,
		arg.HasProject,
		arg.IsComplete,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsComplete,
			&i.MaxSize,
			&i.Discipline,
			&i.CreatedBy,
			&i.ProjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteTeamMember = `-- name: PromoteTeamMember :one
UPDATE team_memberships
SET role = $3
WHERE team_id = $1 AND user_id = $2
RETURNING id, team_id, user_id, role, joined_at
`

type PromoteTeamMemberParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) PromoteTeamMember(ctx context.Context, arg PromoteTeamMemberParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, promoteTeamMember, arg.TeamID, arg.UserID, arg.Role)
	var i TeamMembership
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM team_memberships WHERE team_id = $1 AND user_id = $2
`

type RemoveTeamMemberParams struct {
	TeamID pgtype.UUID `json:"team_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.Exec(ctx, removeTeamMember, arg.TeamID, arg.UserID)
	return err
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams
SET name = $2,
    description = $3,
    discipline = $4,
    max_size = $5,
    is_complete = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, is_complete, max_size, discipline, created_by, project_id, created_at, updated_at
`

type UpdateTeamParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Discipline  pgtype.Text `json:"discipline"`
	MaxSize     int32       `json:"max_size"`
	IsComplete  bool        `json:"is_complete"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Discipline,
		arg.MaxSize,
		arg.IsComplete,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsComplete,
		&i.MaxSize,
		&i.Discipline,
		&i.CreatedBy,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
