// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (auth_user_id, username, email, full_name, discipline, university)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, auth_user_id, username, email, full_name, bio, discipline, university, linkedin_url, github_url, portfolio_url, resume_url, avatar_url, created_at, updated_at
`

type CreateUserParams struct {
	AuthUserID string      `json:"auth_user_id"`
	Username   string      `json:"username"`
	Email      pgtype.Text `json:"email"`
	FullName   string      `json:"full_name"`
	Discipline pgtype.Text `json:"discipline"`
	University pgtype.Text `json:"university"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.AuthUserID,
		arg.Username,
		arg.Email,
		arg.FullName,
		arg.Discipline,
		arg.University,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Bio,
		&i.Discipline,
		&i.University,
		&i.LinkedinUrl,
		&i.GithubUrl,
		&i.PortfolioUrl,
		&i.ResumeUrl,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, auth_user_id, username, email, full_name, bio, discipline, university, linkedin_url, github_url, portfolio_url, resume_url, avatar_url, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Bio,
		&i.Discipline,
		&i.University,
		&i.LinkedinUrl,
		&i.GithubUrl,
		&i.PortfolioUrl,
		&i.ResumeUrl,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByAuthID = `-- name: GetUserByAuthID :one
SELECT id, auth_user_id, username, email, full_name, bio, discipline, university, linkedin_url, github_url, portfolio_url, resume_url, avatar_url, created_at, updated_at FROM users WHERE auth_user_id = $1
`

func (q *Queries) GetUserByAuthID(ctx context.Context, authUserID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAuthID, authUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Bio,
		&i.Discipline,
		&i.University,
		&i.LinkedinUrl,
		&i.GithubUrl,
		&i.PortfolioUrl,
		&i.ResumeUrl,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, auth_user_id, username, email, full_name, bio, discipline, university, linkedin_url, github_url, portfolio_url, resume_url, avatar_url, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Bio,
		&i.Discipline,
		&i.University,
		&i.LinkedinUrl,
		&i.GithubUrl,
		&i.PortfolioUrl,
		&i.ResumeUrl,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserTags = `-- name: ListUserTags :many
SELECT t.id, t.name, t.is_predefined
FROM tags t
JOIN user_tags ut ON ut.tag_id = t.id
WHERE ut.user_id = $1
ORDER BY t.name
`

func (q *Queries) ListUserTags(ctx context.Context, userID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listUserTags, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.IsPredefined); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT DISTINCT u.id, u.auth_user_id, u.username, u.email, u.full_name, u.bio, u.discipline, u.university, u.linkedin_url, u.github_url, u.portfolio_url, u.resume_url, u.avatar_url, u.created_at, u.updated_at
FROM users u
LEFT JOIN user_tags ut ON ut.user_id = u.id
LEFT JOIN tags t ON t.id = ut.tag_id
WHERE ($1::text IS NULL OR u.discipline = $1::text)
  AND ($2::text IS NULL OR t.name = $2::text)
  AND (
    $3::text IS NULL
    OR u.username ILIKE '%' || $3::text || '%'
    OR u.full_name ILIKE '%' || $3::text || '%'
  )
ORDER BY u.full_name
`

type ListUsersParams struct {
	Discipline pgtype.Text `json:"discipline"`
	Tag        pgtype.Text `json:"tag"`
	Search     pgtype.Text `json:"search"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Discipline, arg.Tag, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.AuthUserID,
			&i.Username,
			&i.Email,
			&i.FullName,
			&i.Bio,
			&i.Discipline,
			&i.University,
			&i.LinkedinUrl,
			&i.GithubUrl,
			&i.PortfolioUrl,
			&i.ResumeUrl,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE users
SET full_name = $2,
    bio = $3,
    discipline = $4,
    university = $5,
    linkedin_url = $6,
    github_url = $7,
    portfolio_url = $8,
    resume_url = $9,
    avatar_url = $10,
    updated_at = now()
WHERE id = $1
RETURNING id, auth_user_id, username, email, full_name, bio, discipline, university, linkedin_url, github_url, portfolio_url, resume_url, avatar_url, created_at, updated_at
`

type UpdateProfileParams struct {
	ID           pgtype.UUID `json:"id"`
	FullName     string      `json:"full_name"`
	Bio          pgtype.Text `json:"bio"`
	Discipline   pgtype.Text `json:"discipline"`
	University   pgtype.Text `json:"university"`
	LinkedinUrl  pgtype.Text `json:"linkedin_url"`
	GithubUrl    pgtype.Text `json:"github_url"`
	PortfolioUrl pgtype.Text `json:"portfolio_url"`
	ResumeUrl    pgtype.Text `json:"resume_url"`
	AvatarUrl    pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.ID,
		arg.FullName,
		arg.Bio,
		arg.Discipline,
		arg.University,
		arg.LinkedinUrl,
		arg.GithubUrl,
		arg.PortfolioUrl,
		arg.ResumeUrl,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Bio,
		&i.Discipline,
		&i.University,
		&i.LinkedinUrl,
		&i.GithubUrl,
		&i.PortfolioUrl,
		&i.ResumeUrl,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
