package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"sort"
	"strings"
	"time"

	"github.com/99designs/gqlgen/graphql"
	pgx "github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/local/quorum/apps/api/internal/auth"
	"github.com/local/quorum/apps/api/internal/db"
	"github.com/local/quorum/apps/api/internal/graph/generated"
	"github.com/local/quorum/apps/api/internal/graph/model"
	"github.com/local/quorum/apps/api/internal/storage"
)

const (
	defaultListLimit         = 50
	defaultConversationLimit = 100
)

// BootstrapProfile is the resolver for the bootstrapProfile field.
func (r *mutationResolver) BootstrapProfile(ctx context.Context, input model.BootstrapProfileInput) (*model.User, error) {
	return r.UpsertMyProfile(ctx, model.UpsertMyProfileInput{
		Username:   input.Username,
		Email:      &input.Email,
		FullName:   input.FullName,
		Bio:        input.Bio,
		Discipline: &input.Discipline,
		University: &input.University,
		UserIntent: input.UserIntent,
	})
}

// UpsertMyProfile is the resolver for the upsertMyProfile field.
func (r *mutationResolver) UpsertMyProfile(ctx context.Context, input model.UpsertMyProfileInput) (*model.User, error) {
	subject, ok := auth.SubjectFromContext(ctx)
	if !ok || subject == "" {
		return nil, errors.New("verified Neon Auth token required")
	}

	username := strings.TrimSpace(input.Username)
	fullName := strings.TrimSpace(input.FullName)
	if username == "" {
		return nil, errors.New("username is required")
	}
	if fullName == "" {
		return nil, errors.New("full name is required")
	}

	current, hasProfile := auth.UserFromContext(ctx)
	if !hasProfile {
		if existing, err := r.Queries.GetUserByAuthID(ctx, subject); err == nil {
			current = existing
			hasProfile = true
		} else if !errors.Is(err, pgx.ErrNoRows) {
			return nil, profilePersistenceError(err)
		}
	}

	skills, replaceSkills := profileSkillValues(input.Skills, input.Tags)
	completionSkills := skills
	if hasProfile && !replaceSkills {
		var err error
		completionSkills, err = r.profileTagNames(ctx, current.ID)
		if err != nil {
			return nil, err
		}
	}

	preferredProjectAreas := input.PreferredProjectAreas
	if preferredProjectAreas == nil {
		if hasProfile {
			preferredProjectAreas = current.PreferredProjectAreas
		} else {
			preferredProjectAreas = []string{}
		}
	}

	profileComplete := profileCompleteValues(fullName, input.Bio, input.Discipline, input.University, completionSkills)
	var user db.User
	if err := r.withTx(ctx, func(q *db.Queries) error {
		var err error
		if hasProfile {
			user, err = q.UpdateProfile(ctx, db.UpdateProfileParams{
				ID:                    current.ID,
				FullName:              fullName,
				Bio:                   textOrCurrent(input.Bio, current.Bio),
				Discipline:            textOrCurrent(input.Discipline, current.Discipline),
				University:            textOrCurrent(input.University, current.University),
				LinkedinUrl:           textOrCurrent(input.LinkedinURL, current.LinkedinUrl),
				GithubUrl:             textOrCurrent(input.GithubURL, current.GithubUrl),
				PortfolioUrl:          textOrCurrent(input.PortfolioURL, current.PortfolioUrl),
				ResumeUrl:             textOrCurrent(input.ResumeURL, current.ResumeUrl),
				AvatarUrl:             textOrCurrent(input.AvatarURL, current.AvatarUrl),
				UserIntent:            derefString(input.UserIntent, current.UserIntent),
				ResumeVisibility:      derefResumeVisibility(input.ResumeVisibility, current.ResumeVisibility),
				Discord:               textOrCurrent(input.Discord, current.Discord),
				AvailabilityNote:      textOrCurrent(input.AvailabilityNote, current.AvailabilityNote),
				PreferredProjectAreas: preferredProjectAreas,
				ProfileComplete:       profileComplete,
			})
		} else {
			user, err = q.CreateUser(ctx, db.CreateUserParams{
				AuthUserID:            subject,
				Username:              username,
				Email:                 text(input.Email),
				FullName:              fullName,
				Discipline:            text(input.Discipline),
				University:            text(input.University),
				UserIntent:            derefString(input.UserIntent, "STUDENT"),
				ResumeVisibility:      derefResumeVisibility(input.ResumeVisibility, string(model.ResumeVisibilityPublic)),
				Bio:                   text(input.Bio),
				PreferredProjectAreas: preferredProjectAreas,
				ProfileComplete:       profileComplete,
			})
		}
		if err != nil {
			return profilePersistenceError(err)
		}
		if !replaceSkills {
			return nil
		}
		if err := q.ClearUserTags(ctx, user.ID); err != nil {
			return err
		}
		for _, skill := range skills {
			tag, err := q.UpsertTag(ctx, skill)
			if err != nil {
				return err
			}
			if err := q.AddUserTag(ctx, db.AddUserTagParams{UserID: user.ID, TagID: tag.ID}); err != nil {
				return err
			}
		}
		return nil
	}); err != nil {
		return nil, err
	}
	return r.user(ctx, user)
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (*model.User, error) {
	current, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	skills, replaceSkills := profileSkills(input)
	completionSkills := skills
	if !replaceSkills {
		var err error
		completionSkills, err = r.profileTagNames(ctx, current.ID)
		if err != nil {
			return nil, err
		}
	}
	preferredProjectAreas := input.PreferredProjectAreas
	if preferredProjectAreas == nil {
		preferredProjectAreas = current.PreferredProjectAreas
	}
	var user db.User
	if err := r.withTx(ctx, func(q *db.Queries) error {
		var err error
		user, err = q.UpdateProfile(ctx, db.UpdateProfileParams{
			ID:                    current.ID,
			FullName:              input.FullName,
			Bio:                   textOrCurrent(input.Bio, current.Bio),
			Discipline:            textOrCurrent(input.Discipline, current.Discipline),
			University:            textOrCurrent(input.University, current.University),
			LinkedinUrl:           textOrCurrent(input.LinkedinURL, current.LinkedinUrl),
			GithubUrl:             textOrCurrent(input.GithubURL, current.GithubUrl),
			PortfolioUrl:          textOrCurrent(input.PortfolioURL, current.PortfolioUrl),
			ResumeUrl:             textOrCurrent(input.ResumeURL, current.ResumeUrl),
			AvatarUrl:             textOrCurrent(input.AvatarURL, current.AvatarUrl),
			UserIntent:            derefString(input.UserIntent, current.UserIntent),
			ResumeVisibility:      derefResumeVisibility(input.ResumeVisibility, current.ResumeVisibility),
			Discord:               textOrCurrent(input.Discord, current.Discord),
			AvailabilityNote:      textOrCurrent(input.AvailabilityNote, current.AvailabilityNote),
			PreferredProjectAreas: preferredProjectAreas,
			ProfileComplete:       derefBool(input.ProfileComplete, profileComplete(input, completionSkills, true)),
		})
		if err != nil {
			return profilePersistenceError(err)
		}
		if !replaceSkills {
			return nil
		}
		if err := q.ClearUserTags(ctx, current.ID); err != nil {
			return err
		}
		for _, skill := range skills {
			tag, err := q.UpsertTag(ctx, skill)
			if err != nil {
				return err
			}
			if err := q.AddUserTag(ctx, db.AddUserTagParams{UserID: current.ID, TagID: tag.ID}); err != nil {
				return err
			}
		}
		return nil
	}); err != nil {
		return nil, err
	}
	return r.user(ctx, user)
}

// DeactivateAccount is the resolver for the deactivateAccount field.
func (r *mutationResolver) DeactivateAccount(ctx context.Context, reason *string) (bool, error) {
	current, err := requireActiveUser(ctx)
	if err != nil {
		return false, err
	}
	if err := r.withTx(ctx, func(q *db.Queries) error {
		if err := q.DeactivateUser(ctx, current.ID); err != nil {
			return err
		}
		return r.auditChange(ctx, q, current.ID, "USER_DEACTIVATED", "USER", current.ID, map[string]any{"deactivated": false}, map[string]any{"deactivated": true}, reason)
	}); err != nil {
		return false, err
	}
	return true, nil
}

// CreateTeam is the resolver for the createTeam field.
func (r *mutationResolver) CreateTeam(ctx context.Context, input model.CreateTeamInput) (*model.Team, error) {
	current, err := requireCompleteUser(ctx)
	if err != nil {
		return nil, err
	}
	count, err := r.Queries.CountUserTeams(ctx, current.ID)
	if err != nil {
		return nil, err
	}
	if count > 0 {
		return nil, errors.New("you are already on a team")
	}
	maxSize := 12
	if input.MaxSize != nil {
		maxSize = *input.MaxSize
	}
	var team db.Team
	if err := r.withTx(ctx, func(q *db.Queries) error {
		var err error
		team, err = q.CreateTeam(ctx, db.CreateTeamParams{
			Name:             input.Name,
			Description:      text(input.Description),
			Discipline:       text(input.Discipline),
			MaxSize:          int32(maxSize),
			CreatedBy:        current.ID,
			RecruitingState:  derefTeamRecruiting(input.RecruitingState, string(model.TeamRecruitingStateRecruiting)),
			Visibility:       derefTeamVisibility(input.Visibility, string(model.TeamVisibilityVisible)),
			DiscordLink:      text(input.DiscordLink),
			ExistingSkills:   input.ExistingSkills,
			NeededSkills:     input.NeededSkills,
			ProjectInterests: input.ProjectInterests,
		})
		if err != nil {
			return err
		}
		if _, err := q.AddTeamMember(ctx, db.AddTeamMemberParams{TeamID: team.ID, UserID: current.ID, Role: string(model.TeamRoleLead)}); err != nil {
			return err
		}
		return r.auditChange(ctx, q, current.ID, "TEAM_CREATED", "TEAM", team.ID, map[string]any{}, teamStateSnapshot(team), nil)
	}); err != nil {
		return nil, err
	}
	return r.team(ctx, team)
}

// UpdateTeam is the resolver for the updateTeam field.
func (r *mutationResolver) UpdateTeam(ctx context.Context, id string, input model.UpdateTeamInput) (*model.Team, error) {
	teamID, err := uuid(id)
	if err != nil {
		return nil, err
	}
	if err := r.requireTeamLead(ctx, teamID); err != nil {
		return nil, err
	}
	team, err := r.Queries.UpdateTeam(ctx, db.UpdateTeamParams{
		ID:               teamID,
		Name:             input.Name,
		Description:      text(input.Description),
		Discipline:       text(input.Discipline),
		MaxSize:          int32(input.MaxSize),
		IsComplete:       input.IsComplete,
		RecruitingState:  derefTeamRecruiting(input.RecruitingState, string(model.TeamRecruitingStateRecruiting)),
		Visibility:       derefTeamVisibility(input.Visibility, string(model.TeamVisibilityVisible)),
		DiscordLink:      text(input.DiscordLink),
		ExistingSkills:   input.ExistingSkills,
		NeededSkills:     input.NeededSkills,
		ProjectInterests: input.ProjectInterests,
	})
	if err != nil {
		return nil, err
	}
	if team.ArchivedAt.Valid {
		return nil, nil
	}
	return r.team(ctx, team)
}

// ArchiveTeam is the resolver for the archiveTeam field.
func (r *mutationResolver) ArchiveTeam(ctx context.Context, id string, reason *string) (bool, error) {
	teamID, err := uuid(id)
	if err != nil {
		return false, err
	}
	if err := r.requireLeadOnly(ctx, teamID); err != nil {
		return false, err
	}
	current, _ := requireActiveUser(ctx)
	before, err := r.Queries.GetTeam(ctx, teamID)
	if err != nil {
		return false, err
	}
	if err := r.withTx(ctx, func(q *db.Queries) error {
		if err := q.ArchiveTeam(ctx, teamID); err != nil {
			return err
		}
		after, err := q.GetTeam(ctx, teamID)
		if err != nil {
			return err
		}
		r.notifyUser(ctx, q, before.CreatedBy, "TEAM_ARCHIVED", map[string]any{"teamId": uuidString(teamID), "teamName": before.Name})
		return r.auditChange(ctx, q, current.ID, "TEAM_ARCHIVED", "TEAM", teamID, teamStateSnapshot(before), teamStateSnapshot(after), reason)
	}); err != nil {
		return false, err
	}
	return true, nil
}

// DeleteTeam is the resolver for the deleteTeam field.
func (r *mutationResolver) DeleteTeam(ctx context.Context, id string) (bool, error) {
	teamID, err := uuid(id)
	if err != nil {
		return false, err
	}
	if err := r.requireLeadOnly(ctx, teamID); err != nil {
		return false, err
	}
	return r.ArchiveTeam(ctx, id, nil)
}

// RemoveMember is the resolver for the removeMember field.
func (r *mutationResolver) RemoveMember(ctx context.Context, teamID string, userID string) (bool, error) {
	tid, err := uuid(teamID)
	if err != nil {
		return false, err
	}
	uid, err := uuid(userID)
	if err != nil {
		return false, err
	}
	if err := r.requireTeamLead(ctx, tid); err != nil {
		return false, err
	}
	target, err := r.Queries.GetTeamMembership(ctx, db.GetTeamMembershipParams{TeamID: tid, UserID: uid})
	if err != nil {
		return false, err
	}
	if target.Role == string(model.TeamRoleLead) {
		return false, errors.New("team lead cannot be removed")
	}
	return true, r.Queries.RemoveTeamMember(ctx, db.RemoveTeamMemberParams{TeamID: tid, UserID: uid})
}

// LeaveTeam is the resolver for the leaveTeam field.
func (r *mutationResolver) LeaveTeam(ctx context.Context, teamID string) (bool, error) {
	current, err := requireUser(ctx)
	if err != nil {
		return false, err
	}
	tid, err := uuid(teamID)
	if err != nil {
		return false, err
	}
	members, err := r.Queries.ListTeamMembers(ctx, tid)
	if err != nil {
		return false, err
	}
	for _, member := range members {
		if sameUUID(member.UserID, current.ID) && member.Role == string(model.TeamRoleLead) {
			return false, errors.New("transfer leadership or archive the team before leaving")
		}
	}
	if err := r.Queries.RemoveTeamMember(ctx, db.RemoveTeamMemberParams{TeamID: tid, UserID: current.ID}); err != nil {
		return false, err
	}
	_ = r.audit(ctx, current.ID, "TEAM_MEMBER_LEFT", "TEAM", tid, nil)
	return true, nil
}

// PromoteMember is the resolver for the promoteMember field.
func (r *mutationResolver) PromoteMember(ctx context.Context, teamID string, userID string, role model.TeamRole) (*model.TeamMembership, error) {
	tid, err := uuid(teamID)
	if err != nil {
		return nil, err
	}
	uid, err := uuid(userID)
	if err != nil {
		return nil, err
	}
	if err := r.requireLeadOnly(ctx, tid); err != nil {
		return nil, err
	}
	if role == model.TeamRoleCoLead {
		count, err := r.Queries.CountTeamCoLeads(ctx, tid)
		if err != nil {
			return nil, err
		}
		if count >= 3 {
			return nil, errors.New("teams can have at most three co-leads")
		}
	}
	member, err := r.Queries.PromoteTeamMember(ctx, db.PromoteTeamMemberParams{TeamID: tid, UserID: uid, Role: string(role)})
	if err != nil {
		return nil, err
	}
	return r.teamMembership(ctx, member)
}

// RequestJoin is the resolver for the requestJoin field.
func (r *mutationResolver) RequestJoin(ctx context.Context, teamID string, message *string) (*model.TeamJoinRequest, error) {
	current, err := requireCompleteUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := r.requireDeadlineOpen(ctx); err != nil {
		return nil, err
	}
	tid, err := uuid(teamID)
	if err != nil {
		return nil, err
	}
	if err := r.expireDueWorkflows(ctx, r.Queries); err != nil {
		return nil, err
	}
	team, err := r.Queries.GetTeam(ctx, tid)
	if err != nil {
		return nil, err
	}
	if team.ArchivedAt.Valid || team.RecruitingState != string(model.TeamRecruitingStateRecruiting) {
		return nil, errors.New("team is not accepting join requests")
	}
	memberCount, err := r.Queries.CountTeamMembers(ctx, tid)
	if err != nil {
		return nil, err
	}
	if memberCount >= team.MaxSize {
		return nil, errors.New("team is full")
	}
	userTeams, err := r.Queries.CountUserTeams(ctx, current.ID)
	if err != nil {
		return nil, err
	}
	if userTeams > 0 {
		return nil, errors.New("you are already on a team")
	}
	existing, err := r.Queries.GetJoinRequestForUserTeam(ctx, db.GetJoinRequestForUserTeamParams{TeamID: tid, UserID: current.ID})
	if err == nil {
		if existing.Status == string(model.JoinRequestStatusPending) || existing.Status == string(model.JoinRequestStatusAcceptedPendingConfirmation) {
			return r.joinRequest(ctx, existing)
		}
		return nil, errors.New("you have already requested to join this team")
	}
	if !errors.Is(err, pgx.ErrNoRows) {
		return nil, err
	}
	expiresAt, err := r.confirmationExpiresAt(ctx)
	if err != nil {
		return nil, err
	}
	var request db.TeamJoinRequest
	if err := r.withTx(ctx, func(q *db.Queries) error {
		var err error
		request, err = q.CreateJoinRequest(ctx, db.CreateJoinRequestParams{TeamID: tid, UserID: current.ID, Message: text(message), ExpiresAt: expiresAt})
		if err != nil {
			return err
		}
		members, err := q.ListTeamMembers(ctx, tid)
		if err != nil {
			return err
		}
		for _, member := range members {
			if member.Role == string(model.TeamRoleLead) || member.Role == string(model.TeamRoleCoLead) {
				r.notifyUser(ctx, q, member.UserID, "JOIN_REQUEST_CREATED", map[string]any{"teamId": uuidString(tid), "requestId": uuidString(request.ID), "userId": uuidString(current.ID)})
			}
		}
		return r.auditChange(ctx, q, current.ID, "JOIN_REQUEST_CREATED", "TEAM_JOIN_REQUEST", request.ID, map[string]any{}, statusSnapshot(request.Status), nil)
	}); err != nil {
		return nil, err
	}
	return r.joinRequest(ctx, request)
}

// RespondToJoinRequest is the resolver for the respondToJoinRequest field.
func (r *mutationResolver) RespondToJoinRequest(ctx context.Context, requestID string, accept bool) (*model.TeamJoinRequest, error) {
	id, err := uuid(requestID)
	if err != nil {
		return nil, err
	}
	if err := r.expireDueWorkflows(ctx, r.Queries); err != nil {
		return nil, err
	}
	request, err := r.Queries.GetJoinRequest(ctx, id)
	if err != nil {
		return nil, err
	}
	if err := r.requireTeamLead(ctx, request.TeamID); err != nil {
		return nil, err
	}
	if terminalJoinRequestStatuses[request.Status] || request.Status == string(model.JoinRequestStatusAcceptedPendingConfirmation) {
		return r.joinRequest(ctx, request)
	}
	if request.Status != string(model.JoinRequestStatusPending) {
		return nil, errors.New("join request is not pending")
	}
	status := model.JoinRequestStatusRejected
	expiresAt := pgtype.Timestamptz{}
	if accept {
		status = model.JoinRequestStatusAcceptedPendingConfirmation
		expiresAt, err = r.confirmationExpiresAt(ctx)
		if err != nil {
			return nil, err
		}
	}
	current, _ := requireActiveUser(ctx)
	var updated db.TeamJoinRequest
	if err := r.withTx(ctx, func(q *db.Queries) error {
		var err error
		updated, err = q.RespondToJoinRequest(ctx, db.RespondToJoinRequestParams{ID: id, Status: string(status), ExpiresAt: expiresAt})
		if err != nil {
			return err
		}
		r.notifyUser(ctx, q, request.UserID, "JOIN_REQUEST_REVIEWED", map[string]any{"requestId": uuidString(id), "teamId": uuidString(request.TeamID), "status": string(status)})
		return r.auditChange(ctx, q, current.ID, "JOIN_REQUEST_REVIEWED", "TEAM_JOIN_REQUEST", id, statusSnapshot(request.Status), statusSnapshot(updated.Status), nil)
	}); err != nil {
		return nil, err
	}
	return r.joinRequest(ctx, updated)
}

// ConfirmJoinRequest is the resolver for the confirmJoinRequest field.
func (r *mutationResolver) ConfirmJoinRequest(ctx context.Context, requestID string) (*model.TeamJoinRequest, error) {
	current, err := requireCompleteUser(ctx)
	if err != nil {
		return nil, err
	}
	id, err := uuid(requestID)
	if err != nil {
		return nil, err
	}
	if err := r.expireDueWorkflows(ctx, r.Queries); err != nil {
		return nil, err
	}
	request, err := r.Queries.GetJoinRequest(ctx, id)
	if err != nil {
		return nil, err
	}
	if !sameUUID(request.UserID, current.ID) {
		return nil, errors.New("not authorized")
	}
	if request.Status == string(model.JoinRequestStatusConfirmed) {
		return r.joinRequest(ctx, request)
	}
	expired, err := r.isExpired(ctx, request.ExpiresAt)
	if err != nil {
		return nil, err
	}
	if expired && request.Status == string(model.JoinRequestStatusAcceptedPendingConfirmation) {
		expiredRequest, err := r.Queries.ExpireJoinRequest(ctx, id)
		if err == nil {
			r.notifyUser(ctx, r.Queries, request.UserID, "JOIN_REQUEST_EXPIRED", map[string]any{"requestId": uuidString(id), "teamId": uuidString(request.TeamID)})
			return r.joinRequest(ctx, expiredRequest)
		}
		return nil, err
	}
	if request.Status != string(model.JoinRequestStatusAcceptedPendingConfirmation) {
		return nil, errors.New("join request is not awaiting confirmation")
	}
	userTeams, err := r.Queries.CountUserTeams(ctx, current.ID)
	if err != nil {
		return nil, err
	}
	if userTeams > 0 {
		return nil, errors.New("you are already on a team")
	}
	var updated db.TeamJoinRequest
	if err := r.withTx(ctx, func(q *db.Queries) error {
		if _, err := q.AddTeamMember(ctx, db.AddTeamMemberParams{TeamID: request.TeamID, UserID: request.UserID, Role: string(model.TeamRoleMember)}); err != nil {
			return err
		}
		var err error
		updated, err = q.ConfirmJoinRequest(ctx, id)
		if err != nil {
			return err
		}
		if err := q.WithdrawOtherJoinRequests(ctx, db.WithdrawOtherJoinRequestsParams{UserID: current.ID, ID: id}); err != nil {
			return err
		}
		if err := q.ExpireOtherTeamInvitations(ctx, db.ExpireOtherTeamInvitationsParams{InvitedUserID: current.ID, ID: pgtype.UUID{}}); err != nil {
			return err
		}
		members, err := q.ListTeamMembers(ctx, request.TeamID)
		if err != nil {
			return err
		}
		for _, member := range members {
			if member.Role == string(model.TeamRoleLead) || member.Role == string(model.TeamRoleCoLead) {
				r.notifyUser(ctx, q, member.UserID, "JOIN_REQUEST_CONFIRMED", map[string]any{"requestId": uuidString(id), "teamId": uuidString(request.TeamID), "userId": uuidString(current.ID)})
			}
		}
		return r.auditChange(ctx, q, current.ID, "JOIN_REQUEST_CONFIRMED", "TEAM_JOIN_REQUEST", id, statusSnapshot(request.Status), statusSnapshot(updated.Status), nil)
	}); err != nil {
		return nil, err
	}
	return r.joinRequest(ctx, updated)
}

// InviteTeamMember is the resolver for the inviteTeamMember field.
func (r *mutationResolver) InviteTeamMember(ctx context.Context, teamID string, userID string, message *string) (*model.TeamInvitation, error) {
	current, err := requireCompleteUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := r.requireDeadlineOpen(ctx); err != nil {
		return nil, err
	}
	tid, err := uuid(teamID)
	if err != nil {
		return nil, err
	}
	uid, err := uuid(userID)
	if err != nil {
		return nil, err
	}
	if err := r.requireTeamLead(ctx, tid); err != nil {
		return nil, err
	}
	if err := r.expireDueWorkflows(ctx, r.Queries); err != nil {
		return nil, err
	}
	team, err := r.Queries.GetTeam(ctx, tid)
	if err != nil {
		return nil, err
	}
	if team.ArchivedAt.Valid || team.RecruitingState == string(model.TeamRecruitingStateHidden) {
		return nil, errors.New("team is not accepting invitations")
	}
	memberCount, err := r.Queries.CountTeamMembers(ctx, tid)
	if err != nil {
		return nil, err
	}
	if memberCount >= team.MaxSize {
		return nil, errors.New("team is full")
	}
	invitee, err := r.Queries.GetUser(ctx, uid)
	if err != nil {
		return nil, err
	}
	if invitee.DeactivatedAt.Valid || invitee.ArchivedAt.Valid {
		return nil, errors.New("invitee account is deactivated")
	}
	userTeams, err := r.Queries.CountUserTeams(ctx, uid)
	if err != nil {
		return nil, err
	}
	if userTeams > 0 {
		return nil, errors.New("user is already on a team")
	}
	existing, err := r.Queries.GetTeamInvitationForUserTeam(ctx, db.GetTeamInvitationForUserTeamParams{TeamID: tid, InvitedUserID: uid})
	if err == nil {
		if existing.Status == string(model.TeamInvitationStatusPending) {
			return r.teamInvitation(ctx, existing)
		}
		return nil, errors.New("user has already been invited to this team")
	}
	if !errors.Is(err, pgx.ErrNoRows) {
		return nil, err
	}
	expiresAt, err := r.confirmationExpiresAt(ctx)
	if err != nil {
		return nil, err
	}
	var invitation db.TeamInvitation
	if err := r.withTx(ctx, func(q *db.Queries) error {
		var err error
		invitation, err = q.CreateTeamInvitation(ctx, db.CreateTeamInvitationParams{
			TeamID: tid, InvitedUserID: uid, InvitedBy: current.ID, Message: text(message), ExpiresAt: expiresAt,
		})
		if err != nil {
			return err
		}
		r.notifyUser(ctx, q, uid, "TEAM_INVITATION_CREATED", map[string]any{"teamId": uuidString(tid), "invitationId": uuidString(invitation.ID), "invitedBy": uuidString(current.ID)})
		return r.auditChange(ctx, q, current.ID, "TEAM_INVITATION_CREATED", "TEAM_INVITATION", invitation.ID, map[string]any{}, statusSnapshot(invitation.Status), nil)
	}); err != nil {
		return nil, err
	}
	return r.teamInvitation(ctx, invitation)
}

// RespondToTeamInvitation is the resolver for the respondToTeamInvitation field.
func (r *mutationResolver) RespondToTeamInvitation(ctx context.Context, invitationID string, accept bool) (*model.TeamInvitation, error) {
	current, err := requireCompleteUser(ctx)
	if err != nil {
		return nil, err
	}
	id, err := uuid(invitationID)
	if err != nil {
		return nil, err
	}
	if err := r.expireDueWorkflows(ctx, r.Queries); err != nil {
		return nil, err
	}
	invitation, err := r.Queries.GetTeamInvitation(ctx, id)
	if err != nil {
		return nil, err
	}
	if !sameUUID(invitation.InvitedUserID, current.ID) {
		return nil, errors.New("not authorized")
	}
	if invitation.Status == string(model.TeamInvitationStatusAccepted) {
		return r.teamInvitation(ctx, invitation)
	}
	expired, err := r.isExpired(ctx, invitation.ExpiresAt)
	if err != nil {
		return nil, err
	}
	if expired && invitation.Status == string(model.TeamInvitationStatusPending) {
		expiredInvitation, err := r.Queries.ExpireTeamInvitation(ctx, id)
		if err == nil {
			r.notifyUser(ctx, r.Queries, current.ID, "TEAM_INVITATION_EXPIRED", map[string]any{"invitationId": uuidString(id), "teamId": uuidString(invitation.TeamID)})
			return r.teamInvitation(ctx, expiredInvitation)
		}
		return nil, err
	}
	if invitation.Status != string(model.TeamInvitationStatusPending) {
		if terminalInvitationStatuses[invitation.Status] {
			return r.teamInvitation(ctx, invitation)
		}
		return nil, errors.New("team invitation is not pending")
	}
	status := model.TeamInvitationStatusDeclined
	if accept {
		if err := r.requireDeadlineOpen(ctx); err != nil {
			return nil, err
		}
		userTeams, err := r.Queries.CountUserTeams(ctx, current.ID)
		if err != nil {
			return nil, err
		}
		if userTeams > 0 {
			return nil, errors.New("you are already on a team")
		}
		team, err := r.Queries.GetTeam(ctx, invitation.TeamID)
		if err != nil {
			return nil, err
		}
		memberCount, err := r.Queries.CountTeamMembers(ctx, invitation.TeamID)
		if err != nil {
			return nil, err
		}
		if team.ArchivedAt.Valid || memberCount >= team.MaxSize {
			return nil, errors.New("team is not accepting members")
		}
		status = model.TeamInvitationStatusAccepted
	}
	var updated db.TeamInvitation
	if err := r.withTx(ctx, func(q *db.Queries) error {
		if accept {
			if _, err := q.AddTeamMember(ctx, db.AddTeamMemberParams{TeamID: invitation.TeamID, UserID: current.ID, Role: string(model.TeamRoleMember)}); err != nil {
				return err
			}
			if err := q.ExpireOtherTeamInvitations(ctx, db.ExpireOtherTeamInvitationsParams{InvitedUserID: current.ID, ID: id}); err != nil {
				return err
			}
			if err := q.WithdrawOtherJoinRequests(ctx, db.WithdrawOtherJoinRequestsParams{UserID: current.ID, ID: pgtype.UUID{}}); err != nil {
				return err
			}
		}
		var err error
		updated, err = q.RespondToTeamInvitation(ctx, db.RespondToTeamInvitationParams{ID: id, Status: string(status)})
		if err != nil {
			return err
		}
		members, err := q.ListTeamMembers(ctx, invitation.TeamID)
		if err != nil {
			return err
		}
		for _, member := range members {
			if member.Role == string(model.TeamRoleLead) || member.Role == string(model.TeamRoleCoLead) {
				r.notifyUser(ctx, q, member.UserID, "TEAM_INVITATION_RESPONDED", map[string]any{"invitationId": uuidString(id), "teamId": uuidString(invitation.TeamID), "status": string(status)})
			}
		}
		return r.auditChange(ctx, q, current.ID, "TEAM_INVITATION_RESPONDED", "TEAM_INVITATION", id, statusSnapshot(invitation.Status), statusSnapshot(updated.Status), nil)
	}); err != nil {
		return nil, err
	}
	return r.teamInvitation(ctx, updated)
}

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input model.CreateProjectInput) (*model.Project, error) {
	current, err := requireCompleteUser(ctx)
	if err != nil {
		return nil, err
	}
	minSize := 10
	if input.TeamSizeMin != nil {
		minSize = *input.TeamSizeMin
	}
	maxSize := 12
	if input.TeamSizeMax != nil {
		maxSize = *input.TeamSizeMax
	}
	existing, err := r.Queries.ListProjectsForOwner(ctx, current.ID)
	if err != nil {
		return nil, err
	}
	if len(existing) > 0 {
		return nil, errors.New("users may own only one project in v1")
	}
	lifecycle := derefProjectLifecycle(input.LifecycleState, string(model.ProjectLifecycleStateDraft))
	approval := derefProjectApproval(input.ApprovalState, string(model.ProjectApprovalStateUnverified))
	questions := []byte(derefString(input.ApplicationQuestions, "[]"))
	var project db.Project
	if err := r.withTx(ctx, func(q *db.Queries) error {
		var err error
		project, err = q.CreateProject(ctx, db.CreateProjectParams{
			Title: input.Title, Summary: derefString(input.Summary, ""), Description: input.Description,
			Constraints: text(input.Constraints), Disciplines: input.Disciplines, TeamSizeMin: int32(minSize), TeamSizeMax: int32(maxSize),
			OwnerID: current.ID, FileUrl: text(input.FileURL), VideoUrl: text(input.VideoURL), LifecycleState: lifecycle, ApprovalState: approval,
			RequiredSkills: input.RequiredSkills, NiceToHaveSkills: input.NiceToHaveSkills, Deliverables: text(input.Deliverables),
			Timeline: text(input.Timeline), EvaluationCriteria: text(input.EvaluationCriteria), ExternalResources: input.ExternalResources,
			OwnerContactPreference: text(input.OwnerContactPreference), ApplicationQuestions: questions,
		})
		if err != nil {
			return err
		}
		return r.auditChange(ctx, q, current.ID, "PROJECT_CREATED", "PROJECT", project.ID, map[string]any{}, projectStateSnapshot(project), nil)
	}); err != nil {
		return nil, err
	}
	return r.projectWithOptions(ctx, project, projectHydrationOptionsFromContext(ctx))
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationResolver) UpdateProject(ctx context.Context, id string, input model.UpdateProjectInput) (*model.Project, error) {
	projectID, err := uuid(id)
	if err != nil {
		return nil, err
	}
	if err := r.requireProjectOwner(ctx, projectID); err != nil {
		return nil, err
	}
	before, err := r.Queries.GetProject(ctx, projectID)
	if err != nil {
		return nil, err
	}
	var project db.Project
	if err := r.withTx(ctx, func(q *db.Queries) error {
		var err error
		project, err = q.UpdateProject(ctx, db.UpdateProjectParams{
			ID: projectID, Title: input.Title, Summary: derefString(input.Summary, before.Summary), Description: input.Description, Constraints: textOrCurrent(input.Constraints, before.Constraints),
			Disciplines: input.Disciplines, TeamSizeMin: int32(input.TeamSizeMin), TeamSizeMax: int32(input.TeamSizeMax),
			LifecycleState: lifecycleForProjectUpdate(input.LifecycleState, input.Status, before.LifecycleState),
			FileUrl:        textOrCurrent(input.FileURL, before.FileUrl), VideoUrl: textOrCurrent(input.VideoURL, before.VideoUrl),
			ApprovalState:  derefProjectApproval(input.ApprovalState, before.ApprovalState),
			RequiredSkills: stringsOrCurrent(input.RequiredSkills, before.RequiredSkills), NiceToHaveSkills: stringsOrCurrent(input.NiceToHaveSkills, before.NiceToHaveSkills), Deliverables: textOrCurrent(input.Deliverables, before.Deliverables),
			Timeline: textOrCurrent(input.Timeline, before.Timeline), EvaluationCriteria: textOrCurrent(input.EvaluationCriteria, before.EvaluationCriteria), ExternalResources: stringsOrCurrent(input.ExternalResources, before.ExternalResources),
			OwnerContactPreference: textOrCurrent(input.OwnerContactPreference, before.OwnerContactPreference), ApplicationQuestions: bytesOrCurrent(input.ApplicationQuestions, before.ApplicationQuestions),
		})
		if err != nil {
			return err
		}
		applications, err := q.ListProjectApplications(ctx, projectID)
		if err != nil {
			return err
		}
		for _, app := range applications {
			r.notifyUser(ctx, q, app.ApplicantID, "PROJECT_EDITED", map[string]any{"projectId": uuidString(projectID), "applicationId": uuidString(app.ID)})
		}
		current, _ := requireActiveUser(ctx)
		return r.auditChange(ctx, q, current.ID, "PROJECT_UPDATED", "PROJECT", projectID, projectStateSnapshot(before), projectStateSnapshot(project), nil)
	}); err != nil {
		return nil, err
	}
	return r.project(ctx, project)
}

// SubmitProjectForApproval is the resolver for the submitProjectForApproval field.
func (r *mutationResolver) SubmitProjectForApproval(ctx context.Context, projectID string) (*model.Project, error) {
	pid, err := uuid(projectID)
	if err != nil {
		return nil, err
	}
	if err := r.requireProjectOwner(ctx, pid); err != nil {
		return nil, err
	}
	before, err := r.Queries.GetProject(ctx, pid)
	if err != nil {
		return nil, err
	}
	var project db.Project
	current, _ := requireActiveUser(ctx)
	if err := r.withTx(ctx, func(q *db.Queries) error {
		var err error
		project, err = q.UpdateProjectApprovalState(ctx, db.UpdateProjectApprovalStateParams{ID: pid, ApprovalState: string(model.ProjectApprovalStateSubmittedForApproval)})
		if err != nil {
			return err
		}
		admins, _ := q.ListAdminUsers(ctx)
		for _, admin := range admins {
			r.notifyUser(ctx, q, admin.ID, "PROJECT_APPROVAL_SUBMITTED", map[string]any{"projectId": uuidString(pid)})
		}
		return r.auditChange(ctx, q, current.ID, "PROJECT_APPROVAL_SUBMITTED", "PROJECT", pid, projectStateSnapshot(before), projectStateSnapshot(project), nil)
	}); err != nil {
		return nil, err
	}
	return r.project(ctx, project)
}

// ReviewProjectApproval is the resolver for the reviewProjectApproval field.
func (r *mutationResolver) ReviewProjectApproval(ctx context.Context, projectID string, approvalState model.ProjectApprovalState, reason *string) (*model.Project, error) {
	current, err := r.requireAdmin(ctx)
	if err != nil {
		return nil, err
	}
	pid, err := uuid(projectID)
	if err != nil {
		return nil, err
	}
	before, err := r.Queries.GetProject(ctx, pid)
	if err != nil {
		return nil, err
	}
	var project db.Project
	if err := r.withTx(ctx, func(q *db.Queries) error {
		var err error
		project, err = q.UpdateProjectApprovalState(ctx, db.UpdateProjectApprovalStateParams{ID: pid, ApprovalState: string(approvalState)})
		if err != nil {
			return err
		}
		r.notifyUser(ctx, q, before.OwnerID, "PROJECT_APPROVAL_REVIEWED", map[string]any{"projectId": uuidString(pid), "approvalState": string(approvalState)})
		return r.auditChange(ctx, q, current.ID, "PROJECT_APPROVAL_REVIEWED", "PROJECT", pid, projectStateSnapshot(before), projectStateSnapshot(project), reason)
	}); err != nil {
		return nil, err
	}
	return r.project(ctx, project)
}

// ArchiveProject is the resolver for the archiveProject field.
func (r *mutationResolver) ArchiveProject(ctx context.Context, id string, reason *string) (bool, error) {
	projectID, err := uuid(id)
	if err != nil {
		return false, err
	}
	if err := r.requireProjectOwner(ctx, projectID); err != nil {
		return false, err
	}
	before, err := r.Queries.GetProject(ctx, projectID)
	if err != nil {
		return false, err
	}
	current, _ := requireActiveUser(ctx)
	if err := r.withTx(ctx, func(q *db.Queries) error {
		if err := q.ArchiveProject(ctx, projectID); err != nil {
			return err
		}
		after, err := q.GetProject(ctx, projectID)
		if err != nil {
			return err
		}
		r.notifyUser(ctx, q, before.OwnerID, "PROJECT_ARCHIVED", map[string]any{"projectId": uuidString(projectID)})
		return r.auditChange(ctx, q, current.ID, "PROJECT_ARCHIVED", "PROJECT", projectID, projectStateSnapshot(before), projectStateSnapshot(after), reason)
	}); err != nil {
		return false, err
	}
	return true, nil
}

// DeleteProject is the resolver for the deleteProject field.
func (r *mutationResolver) DeleteProject(ctx context.Context, id string) (bool, error) {
	projectID, err := uuid(id)
	if err != nil {
		return false, err
	}
	if err := r.requireProjectOwner(ctx, projectID); err != nil {
		return false, err
	}
	return r.ArchiveProject(ctx, id, nil)
}

// ApplyToProjectInput is the resolver for the applyToProjectInput field.
func (r *mutationResolver) ApplyToProjectInput(ctx context.Context, input model.ApplyToProjectInput) (*model.ProjectApplication, error) {
	return r.applyToProject(ctx, input.ProjectID, input.TeamID, input.Message, []byte(derefString(input.Answers, "[]")))
}

// ApplyToProject is the resolver for the applyToProject field.
func (r *mutationResolver) ApplyToProject(ctx context.Context, projectID string, teamID string, message *string) (*model.ProjectApplication, error) {
	return r.applyToProject(ctx, projectID, teamID, message, []byte("[]"))
}

// RespondToApplication is the resolver for the respondToApplication field.
func (r *mutationResolver) RespondToApplication(ctx context.Context, applicationID string, accept bool) (bool, error) {
	id, err := uuid(applicationID)
	if err != nil {
		return false, err
	}
	application, err := r.Queries.GetProjectApplication(ctx, id)
	if err != nil {
		return false, err
	}
	if err := r.requireProjectOwner(ctx, application.ProjectID); err != nil {
		return false, err
	}
	if accept {
		_, err := r.SendProjectOffer(ctx, applicationID, nil)
		return err == nil, err
	}
	_, err = r.RejectApplication(ctx, applicationID, nil)
	return err == nil, err
}

// RejectApplication is the resolver for the rejectApplication field.
func (r *mutationResolver) RejectApplication(ctx context.Context, applicationID string, message *string) (*model.ProjectApplication, error) {
	id, err := uuid(applicationID)
	if err != nil {
		return nil, err
	}
	application, err := r.Queries.GetProjectApplication(ctx, id)
	if err != nil {
		return nil, err
	}
	if err := r.requireProjectOwner(ctx, application.ProjectID); err != nil {
		return nil, err
	}
	if terminalApplicationStatuses[application.Status] {
		return r.projectApplication(ctx, application)
	}
	var updated db.ProjectApplication
	current, _ := requireActiveUser(ctx)
	if err := r.withTx(ctx, func(q *db.Queries) error {
		var err error
		updated, err = q.RespondToApplication(ctx, db.RespondToApplicationParams{ID: id, Status: string(model.ApplicationStatusRejected), ReviewMessage: text(message)})
		if err != nil {
			return err
		}
		r.notifyUser(ctx, q, application.ApplicantID, "PROJECT_APPLICATION_REJECTED", map[string]any{"applicationId": uuidString(id), "projectId": uuidString(application.ProjectID), "teamId": uuidString(application.TeamID)})
		return r.auditChange(ctx, q, current.ID, "PROJECT_APPLICATION_REJECTED", "PROJECT_APPLICATION", id, statusSnapshot(application.Status), statusSnapshot(updated.Status), message)
	}); err != nil {
		return nil, err
	}
	return r.projectApplication(ctx, updated)
}

// SendProjectOffer is the resolver for the sendProjectOffer field.
func (r *mutationResolver) SendProjectOffer(ctx context.Context, applicationID string, message *string) (*model.ProjectApplication, error) {
	id, err := uuid(applicationID)
	if err != nil {
		return nil, err
	}
	application, err := r.Queries.GetProjectApplication(ctx, id)
	if err != nil {
		return nil, err
	}
	if err := r.requireProjectOwner(ctx, application.ProjectID); err != nil {
		return nil, err
	}
	if application.Status == string(model.ApplicationStatusOfferSent) {
		return r.projectApplication(ctx, application)
	}
	if application.Status != string(model.ApplicationStatusSubmitted) && application.Status != string(model.ApplicationStatusUnderReview) && application.Status != string(model.ApplicationStatusMessageSent) {
		return nil, errors.New("application cannot receive an offer in its current state")
	}
	if err := r.requireDeadlineOpen(ctx); err != nil {
		return nil, err
	}
	expiresAt, err := r.confirmationExpiresAt(ctx)
	if err != nil {
		return nil, err
	}
	var updated db.ProjectApplication
	current, _ := requireActiveUser(ctx)
	if err := r.withTx(ctx, func(q *db.Queries) error {
		var err error
		updated, err = q.SendProjectOffer(ctx, db.SendProjectOfferParams{ID: id, OfferMessage: text(message), ExpiresAt: expiresAt})
		if err != nil {
			return err
		}
		if _, err := q.UpdateProjectLifecycleState(ctx, db.UpdateProjectLifecycleStateParams{ID: application.ProjectID, LifecycleState: string(model.ProjectLifecycleStateOfferSent)}); err != nil {
			return err
		}
		if err := q.UpdateTeamCapstoneState(ctx, db.UpdateTeamCapstoneStateParams{ID: application.TeamID, CapstoneState: string(model.TeamCapstoneStateOfferReceived)}); err != nil {
			return err
		}
		members, err := q.ListTeamMembers(ctx, application.TeamID)
		if err != nil {
			return err
		}
		for _, member := range members {
			if member.Role == string(model.TeamRoleLead) || member.Role == string(model.TeamRoleCoLead) {
				r.notifyUser(ctx, q, member.UserID, "PROJECT_OFFER_SENT", map[string]any{"applicationId": uuidString(id), "projectId": uuidString(application.ProjectID), "teamId": uuidString(application.TeamID), "expiresAt": timeString(expiresAt)})
			}
		}
		return r.auditChange(ctx, q, current.ID, "PROJECT_OFFER_SENT", "PROJECT_APPLICATION", id, statusSnapshot(application.Status), statusSnapshot(updated.Status), message)
	}); err != nil {
		return nil, err
	}
	return r.projectApplication(ctx, updated)
}

// ConfirmProjectOfferByTeam is the resolver for the confirmProjectOfferByTeam field.
func (r *mutationResolver) ConfirmProjectOfferByTeam(ctx context.Context, applicationID string) (*model.ProjectApplication, error) {
	id, err := uuid(applicationID)
	if err != nil {
		return nil, err
	}
	application, err := r.Queries.GetProjectApplication(ctx, id)
	if err != nil {
		return nil, err
	}
	if err := r.requireTeamLead(ctx, application.TeamID); err != nil {
		return nil, err
	}
	if application.Status == string(model.ApplicationStatusTeamConfirmed) || application.Status == string(model.ApplicationStatusMatched) {
		return r.projectApplication(ctx, application)
	}
	expired, err := r.isExpired(ctx, application.ExpiresAt)
	if err != nil {
		return nil, err
	}
	if expired && application.Status == string(model.ApplicationStatusOfferSent) {
		expiredApplication, err := r.Queries.ExpireProjectOffer(ctx, id)
		if err == nil {
			r.notifyUser(ctx, r.Queries, application.ApplicantID, "PROJECT_OFFER_EXPIRED", map[string]any{"applicationId": uuidString(id), "projectId": uuidString(application.ProjectID)})
			return r.projectApplication(ctx, expiredApplication)
		}
		return nil, err
	}
	if application.Status != string(model.ApplicationStatusOfferSent) {
		return nil, errors.New("project offer is not awaiting team confirmation")
	}
	var updated db.ProjectApplication
	current, _ := requireActiveUser(ctx)
	if err := r.withTx(ctx, func(q *db.Queries) error {
		var err error
		updated, err = q.ConfirmProjectOfferByTeam(ctx, id)
		if err != nil {
			return err
		}
		project, err := q.GetProject(ctx, application.ProjectID)
		if err != nil {
			return err
		}
		r.notifyUser(ctx, q, project.OwnerID, "PROJECT_OFFER_TEAM_CONFIRMED", map[string]any{"applicationId": uuidString(id), "projectId": uuidString(application.ProjectID), "teamId": uuidString(application.TeamID)})
		return r.auditChange(ctx, q, current.ID, "PROJECT_OFFER_TEAM_CONFIRMED", "PROJECT_APPLICATION", id, statusSnapshot(application.Status), statusSnapshot(updated.Status), nil)
	}); err != nil {
		return nil, err
	}
	return r.projectApplication(ctx, updated)
}

// ConfirmProjectOfferByOwner is the resolver for the confirmProjectOfferByOwner field.
func (r *mutationResolver) ConfirmProjectOfferByOwner(ctx context.Context, applicationID string) (*model.ProjectApplication, error) {
	id, err := uuid(applicationID)
	if err != nil {
		return nil, err
	}
	application, err := r.Queries.GetProjectApplication(ctx, id)
	if err != nil {
		return nil, err
	}
	if err := r.requireProjectOwner(ctx, application.ProjectID); err != nil {
		return nil, err
	}
	if application.Status == string(model.ApplicationStatusMatched) {
		return r.projectApplication(ctx, application)
	}
	expired, err := r.isExpired(ctx, application.ExpiresAt)
	if err != nil {
		return nil, err
	}
	if expired && (application.Status == string(model.ApplicationStatusOfferSent) || application.Status == string(model.ApplicationStatusTeamConfirmed)) {
		expiredApplication, err := r.Queries.ExpireProjectOffer(ctx, id)
		if err == nil {
			r.notifyUser(ctx, r.Queries, application.ApplicantID, "PROJECT_OFFER_EXPIRED", map[string]any{"applicationId": uuidString(id), "projectId": uuidString(application.ProjectID)})
			return r.projectApplication(ctx, expiredApplication)
		}
		return nil, err
	}
	if application.Status != string(model.ApplicationStatusTeamConfirmed) {
		return nil, errors.New("project offer is not awaiting owner confirmation")
	}
	var updated db.ProjectApplication
	current, _ := requireActiveUser(ctx)
	if err := r.withTx(ctx, func(q *db.Queries) error {
		var err error
		updated, err = q.ConfirmProjectOfferByOwner(ctx, id)
		if err != nil {
			return err
		}
		if _, err := q.ClaimProject(ctx, db.ClaimProjectParams{ID: application.ProjectID, TeamID: application.TeamID}); err != nil {
			return err
		}
		if err := q.UpdateTeamCapstoneState(ctx, db.UpdateTeamCapstoneStateParams{ID: application.TeamID, CapstoneState: string(model.TeamCapstoneStateMatched)}); err != nil {
			return err
		}
		if err := q.WithdrawCompetingTeamApplications(ctx, db.WithdrawCompetingTeamApplicationsParams{TeamID: application.TeamID, ID: id}); err != nil {
			return err
		}
		if err := q.WithdrawCompetingProjectApplications(ctx, db.WithdrawCompetingProjectApplicationsParams{ProjectID: application.ProjectID, ID: id}); err != nil {
			return err
		}
		members, err := q.ListTeamMembers(ctx, application.TeamID)
		if err != nil {
			return err
		}
		for _, member := range members {
			r.notifyUser(ctx, q, member.UserID, "PROJECT_MATCH_FINALIZED", map[string]any{"applicationId": uuidString(id), "projectId": uuidString(application.ProjectID), "teamId": uuidString(application.TeamID)})
		}
		return r.auditChange(ctx, q, current.ID, "PROJECT_MATCH_FINALIZED", "PROJECT_APPLICATION", id, statusSnapshot(application.Status), statusSnapshot(updated.Status), nil)
	}); err != nil {
		return nil, err
	}
	return r.projectApplication(ctx, updated)
}

// WithdrawApplication is the resolver for the withdrawApplication field.
func (r *mutationResolver) WithdrawApplication(ctx context.Context, applicationID string) (*model.ProjectApplication, error) {
	id, err := uuid(applicationID)
	if err != nil {
		return nil, err
	}
	application, err := r.Queries.GetProjectApplication(ctx, id)
	if err != nil {
		return nil, err
	}
	if err := r.requireTeamLead(ctx, application.TeamID); err != nil {
		return nil, err
	}
	if terminalApplicationStatuses[application.Status] {
		return r.projectApplication(ctx, application)
	}
	var updated db.ProjectApplication
	current, _ := requireActiveUser(ctx)
	if err := r.withTx(ctx, func(q *db.Queries) error {
		var err error
		updated, err = q.WithdrawApplication(ctx, id)
		if err != nil {
			return err
		}
		project, err := q.GetProject(ctx, application.ProjectID)
		if err == nil {
			r.notifyUser(ctx, q, project.OwnerID, "PROJECT_APPLICATION_WITHDRAWN", map[string]any{"applicationId": uuidString(id), "projectId": uuidString(application.ProjectID), "teamId": uuidString(application.TeamID)})
		}
		return r.auditChange(ctx, q, current.ID, "PROJECT_APPLICATION_WITHDRAWN", "PROJECT_APPLICATION", id, statusSnapshot(application.Status), statusSnapshot(updated.Status), nil)
	}); err != nil {
		return nil, err
	}
	return r.projectApplication(ctx, updated)
}

// AssociateProject is the resolver for the associateProject field.
func (r *mutationResolver) AssociateProject(ctx context.Context, teamID string, projectID string) (*model.Team, error) {
	tid, err := uuid(teamID)
	if err != nil {
		return nil, err
	}
	pid, err := uuid(projectID)
	if err != nil {
		return nil, err
	}
	if err := r.requireTeamLead(ctx, tid); err != nil {
		return nil, err
	}
	team, err := r.Queries.AssociateProject(ctx, db.AssociateProjectParams{ID: tid, ProjectID: pid})
	if err != nil {
		return nil, err
	}
	return r.team(ctx, team)
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, receiverID string, body string) (*model.Message, error) {
	current, err := requireActiveUser(ctx)
	if err != nil {
		return nil, err
	}
	rid, err := uuid(receiverID)
	if err != nil {
		return nil, err
	}
	message, err := r.Queries.SendMessage(ctx, db.SendMessageParams{SenderID: current.ID, ReceiverID: rid, Body: body})
	if err != nil {
		return nil, err
	}
	r.notifyUser(ctx, r.Queries, rid, "MESSAGE_SENT", map[string]any{"messageId": uuidString(message.ID), "senderId": uuidString(current.ID)})
	return r.message(ctx, message)
}

// MarkRead is the resolver for the markRead field.
func (r *mutationResolver) MarkRead(ctx context.Context, messageID string) (bool, error) {
	current, err := requireUser(ctx)
	if err != nil {
		return false, err
	}
	id, err := uuid(messageID)
	if err != nil {
		return false, err
	}
	message, err := r.Queries.GetMessage(ctx, id)
	if err != nil {
		return false, err
	}
	if !sameUUID(message.ReceiverID, current.ID) {
		return false, errors.New("not authorized")
	}
	_, err = r.Queries.MarkMessageRead(ctx, db.MarkMessageReadParams{ID: id, ReceiverID: current.ID})
	return err == nil, err
}

// MarkNotificationRead is the resolver for the markNotificationRead field.
func (r *mutationResolver) MarkNotificationRead(ctx context.Context, notificationID string) (bool, error) {
	current, err := requireUser(ctx)
	if err != nil {
		return false, err
	}
	id, err := uuid(notificationID)
	if err != nil {
		return false, err
	}
	notification, err := r.Queries.GetNotification(ctx, id)
	if err != nil {
		return false, err
	}
	if !sameUUID(notification.UserID, current.ID) {
		return false, errors.New("not authorized")
	}
	_, err = r.Queries.MarkNotificationRead(ctx, db.MarkNotificationReadParams{ID: id, UserID: current.ID})
	return err == nil, err
}

// SetUniversalDeadline is the resolver for the setUniversalDeadline field.
func (r *mutationResolver) SetUniversalDeadline(ctx context.Context, deadlineAt string, reason *string) (*model.Deadline, error) {
	current, err := r.requireAdmin(ctx)
	if err != nil {
		return nil, err
	}
	parsed, err := time.Parse(time.RFC3339, deadlineAt)
	if err != nil {
		return nil, err
	}
	before, _ := r.Queries.GetUniversalDeadline(ctx)
	var deadline db.UniversalDeadline
	if err := r.withTx(ctx, func(q *db.Queries) error {
		var err error
		deadline, err = q.UpsertUniversalDeadline(ctx, db.UpsertUniversalDeadlineParams{DeadlineAt: pgtime(parsed), UpdatedBy: current.ID})
		if err != nil {
			return err
		}
		if err := r.expireDueWorkflows(ctx, q); err != nil {
			return err
		}
		users, err := q.ListUsers(ctx, db.ListUsersParams{Discipline: pgtype.Text{}, Tag: pgtype.Text{}, Search: pgtype.Text{}})
		if err == nil {
			for _, user := range users {
				r.notifyUser(ctx, q, user.ID, "UNIVERSAL_DEADLINE_CHANGED", map[string]any{"deadlineAt": timeString(deadline.DeadlineAt)})
			}
		}
		return r.auditChange(ctx, q, current.ID, "UNIVERSAL_DEADLINE_CHANGED", "DEADLINE", pgtype.UUID{}, map[string]any{"deadlineAt": timeString(before.DeadlineAt)}, map[string]any{"deadlineAt": timeString(deadline.DeadlineAt)}, reason)
	}); err != nil {
		return nil, err
	}
	return r.deadline(ctx, deadline)
}

// SignUpload is the resolver for the signUpload field.
func (r *mutationResolver) SignUpload(ctx context.Context, input model.SignUploadInput) (*model.UploadSignature, error) {
	current, err := requireActiveUser(ctx)
	if err != nil {
		return nil, err
	}
	if r.Storage == nil {
		return nil, errors.New("storage signing is not configured")
	}
	post, err := r.Storage.PresignPost(ctx, storage.AssetKind(input.Kind), uuidString(current.ID), input.Filename, input.ContentType, int64(input.Size))
	if err != nil {
		return nil, err
	}
	fields := make([]*model.UploadField, 0, len(post.Fields))
	names := make([]string, 0, len(post.Fields))
	for name := range post.Fields {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		fields = append(fields, &model.UploadField{Name: name, Value: post.Fields[name]})
	}
	var publicURL *string
	if post.PublicURL != "" {
		publicURL = &post.PublicURL
	}
	return &model.UploadSignature{
		URL:       post.URL,
		Key:       post.Key,
		PublicURL: publicURL,
		ExpiresAt: post.ExpiresAt.UTC().Format("2006-01-02T15:04:05Z07:00"),
		Fields:    fields,
	}, nil
}

// RemoveUser is the resolver for the removeUser field.
func (r *mutationResolver) RemoveUser(ctx context.Context, userID string, reason *string) (bool, error) {
	current, err := r.requireAdmin(ctx)
	if err != nil {
		return false, err
	}
	id, err := uuid(userID)
	if err != nil {
		return false, err
	}
	target, err := r.Queries.GetUser(ctx, id)
	if err != nil {
		return false, err
	}
	if err := r.withTx(ctx, func(q *db.Queries) error {
		if err := q.DeactivateUser(ctx, id); err != nil {
			return err
		}
		r.notifyUser(ctx, q, id, "USER_DEACTIVATED_BY_ADMIN", map[string]any{"userId": uuidString(id)})
		return r.auditChange(ctx, q, current.ID, "USER_DEACTIVATED_BY_ADMIN", "USER", id, map[string]any{"deactivatedAt": timeStringPointer(target.DeactivatedAt)}, map[string]any{"deactivated": true}, reason)
	}); err != nil {
		return false, err
	}
	return true, nil
}

// RemoveTeam is the resolver for the removeTeam field.
func (r *mutationResolver) RemoveTeam(ctx context.Context, teamID string, reason *string) (bool, error) {
	current, err := r.requireAdmin(ctx)
	if err != nil {
		return false, err
	}
	id, err := uuid(teamID)
	if err != nil {
		return false, err
	}
	before, err := r.Queries.GetTeam(ctx, id)
	if err != nil {
		return false, err
	}
	if err := r.withTx(ctx, func(q *db.Queries) error {
		if err := q.ArchiveTeam(ctx, id); err != nil {
			return err
		}
		after, err := q.GetTeam(ctx, id)
		if err != nil {
			return err
		}
		members, _ := q.ListTeamMembers(ctx, id)
		for _, member := range members {
			r.notifyUser(ctx, q, member.UserID, "TEAM_ARCHIVED_BY_ADMIN", map[string]any{"teamId": uuidString(id)})
		}
		return r.auditChange(ctx, q, current.ID, "TEAM_ARCHIVED_BY_ADMIN", "TEAM", id, teamStateSnapshot(before), teamStateSnapshot(after), reason)
	}); err != nil {
		return false, err
	}
	return true, nil
}

// RemoveProject is the resolver for the removeProject field.
func (r *mutationResolver) RemoveProject(ctx context.Context, projectID string, reason *string) (bool, error) {
	current, err := r.requireAdmin(ctx)
	if err != nil {
		return false, err
	}
	id, err := uuid(projectID)
	if err != nil {
		return false, err
	}
	before, err := r.Queries.GetProject(ctx, id)
	if err != nil {
		return false, err
	}
	if err := r.withTx(ctx, func(q *db.Queries) error {
		if err := q.ArchiveProject(ctx, id); err != nil {
			return err
		}
		after, err := q.GetProject(ctx, id)
		if err != nil {
			return err
		}
		r.notifyUser(ctx, q, before.OwnerID, "PROJECT_ARCHIVED_BY_ADMIN", map[string]any{"projectId": uuidString(id)})
		return r.auditChange(ctx, q, current.ID, "PROJECT_ARCHIVED_BY_ADMIN", "PROJECT", id, projectStateSnapshot(before), projectStateSnapshot(after), reason)
	}); err != nil {
		return false, err
	}
	return true, nil
}

// AuthState is the resolver for the authState field.
func (r *queryResolver) AuthState(ctx context.Context) (*model.AuthState, error) {
	current, ok := auth.UserFromContext(ctx)
	if !ok {
		if subject, hasSubject := auth.SubjectFromContext(ctx); !hasSubject || subject == "" {
			return &model.AuthState{}, nil
		}
		return &model.AuthState{Authenticated: true}, nil
	}
	var profile *model.User
	var err error
	if graphql.FieldRequested(ctx, "profile.tags") {
		profile, err = r.user(ctx, current)
	} else {
		profile, err = r.shallowUser(ctx, current)
	}
	if err != nil {
		return nil, err
	}
	return &model.AuthState{
		Authenticated:   true,
		HasProfile:      true,
		ProfileComplete: current.ProfileComplete,
		Profile:         profile,
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	current, ok := auth.UserFromContext(ctx)
	if !ok {
		return nil, nil
	}
	return r.user(ctx, current)
}

// DashboardContext is the resolver for the dashboardContext field.
func (r *queryResolver) DashboardContext(ctx context.Context) (*model.DashboardContext, error) {
	current, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	teams := make([]*model.Team, 0)
	if graphql.FieldRequested(ctx, "myTeams") {
		teamRows, err := r.Queries.ListTeamsForUser(ctx, current.ID)
		if err != nil {
			return nil, err
		}
		teams = make([]*model.Team, 0, len(teamRows))
		for _, team := range teamRows {
			mapped, err := r.teamWithOptions(ctx, team, teamHydrationOptions{
				includeCreatedBy:   true,
				includeMembers:     true,
				includeProject:     true,
				includePermissions: true,
				includeMemberTeam:  true,
				creatorTags:        false,
			})
			if err != nil {
				return nil, err
			}
			teams = append(teams, mapped)
		}
	}
	projects := make([]*model.Project, 0)
	if graphql.FieldRequested(ctx, "myProjects") {
		projectRows, err := r.Queries.ListProjectsForOwner(ctx, current.ID)
		if err != nil {
			return nil, err
		}
		projects = make([]*model.Project, 0, len(projectRows))
		for _, project := range projectRows {
			mapped, err := r.projectWithOptions(ctx, project, projectHydrationOptions{
				includeApplications: true,
			})
			if err != nil {
				return nil, err
			}
			projects = append(projects, mapped)
		}
	}
	invitations := make([]*model.TeamInvitation, 0)
	if graphql.FieldRequested(ctx, "myInvitations") {
		invitations, err = r.MyTeamInvitations(ctx)
		if err != nil {
			return nil, err
		}
	}
	var unreadMessages int32
	if graphql.FieldRequested(ctx, "unreadMessages") {
		unreadMessages, err = r.Queries.CountUnreadMessages(ctx, current.ID)
		if err != nil {
			return nil, err
		}
	}
	var unreadNotifications int32
	if graphql.FieldRequested(ctx, "unreadNotifications") {
		unreadNotifications, err = r.Queries.CountUnreadNotifications(ctx, current.ID)
		if err != nil {
			return nil, err
		}
	}
	var deadline *model.Deadline
	if graphql.FieldRequested(ctx, "universalDeadline") {
		deadline, _ = r.UniversalDeadline(ctx)
	}
	isAdmin := false
	if graphql.FieldRequested(ctx, "isAdmin") {
		isAdmin, _ = r.cachedIsAdmin(ctx, current.ID)
	}
	return &model.DashboardContext{
		MyTeams: teams, MyProjects: projects, MyInvitations: invitations,
		UnreadMessages: int(unreadMessages), UnreadNotifications: int(unreadNotifications),
		UniversalDeadline: deadline, IsAdmin: isAdmin,
	}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, username string) (*model.User, error) {
	user, err := r.Queries.GetUserByUsername(ctx, username)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return r.user(ctx, user)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, discipline *string, tag *string, search *string) ([]*model.User, error) {
	users, err := r.Queries.ListUsers(ctx, db.ListUsersParams{Discipline: text(discipline), Tag: text(tag), Search: text(search)})
	if err != nil {
		return nil, err
	}
	if len(users) > defaultListLimit {
		users = users[:defaultListLimit]
	}
	out := make([]*model.User, 0, len(users))
	for _, user := range users {
		mapped, err := r.user(ctx, user)
		if err != nil {
			return nil, err
		}
		out = append(out, mapped)
	}
	return out, nil
}

// Team is the resolver for the team field.
func (r *queryResolver) Team(ctx context.Context, id string) (*model.Team, error) {
	teamID, err := uuid(id)
	if err != nil {
		return nil, err
	}
	team, err := r.Queries.GetTeam(ctx, teamID)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return r.team(ctx, team)
}

// Teams is the resolver for the teams field.
func (r *queryResolver) Teams(ctx context.Context, discipline *string, hasProject *bool, isComplete *bool, search *string) ([]*model.Team, error) {
	teams, err := r.Queries.ListTeams(ctx, db.ListTeamsParams{
		Discipline: text(discipline),
		HasProject: boolValue(hasProject),
		IsComplete: boolValue(isComplete),
		Search:     text(search),
	})
	if err != nil {
		return nil, err
	}
	if len(teams) > defaultListLimit {
		teams = teams[:defaultListLimit]
	}
	out := make([]*model.Team, 0, len(teams))
	for _, team := range teams {
		mapped, err := r.team(ctx, team)
		if err != nil {
			return nil, err
		}
		out = append(out, mapped)
	}
	return out, nil
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id string) (*model.Project, error) {
	projectID, err := uuid(id)
	if err != nil {
		return nil, err
	}
	project, err := r.Queries.GetProject(ctx, projectID)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	if project.ArchivedAt.Valid {
		return nil, nil
	}
	return r.project(ctx, project)
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context, discipline *string, status *model.ProjectLifecycleState, search *string) ([]*model.Project, error) {
	var statusText *string
	if status != nil {
		value := string(*status)
		statusText = &value
	}
	projects, err := r.Queries.ListProjects(ctx, db.ListProjectsParams{Discipline: text(discipline), Status: text(statusText), Search: text(search)})
	if err != nil {
		return nil, err
	}
	if len(projects) > defaultListLimit {
		projects = projects[:defaultListLimit]
	}
	out := make([]*model.Project, 0, len(projects))
	for _, project := range projects {
		mapped, err := r.projectWithOptions(ctx, project, projectHydrationOptionsFromContext(ctx))
		if err != nil {
			return nil, err
		}
		out = append(out, mapped)
	}
	return out, nil
}

// MyMessages is the resolver for the myMessages field.
func (r *queryResolver) MyMessages(ctx context.Context, withUser string) ([]*model.Message, error) {
	current, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	otherID, err := uuid(withUser)
	if err != nil {
		return nil, err
	}
	messages, err := r.Queries.ListMessagesWithUser(ctx, db.ListMessagesWithUserParams{SenderID: current.ID, ReceiverID: otherID})
	if err != nil {
		return nil, err
	}
	if len(messages) > defaultConversationLimit {
		messages = messages[len(messages)-defaultConversationLimit:]
	}
	out := make([]*model.Message, 0, len(messages))
	for _, message := range messages {
		mapped, err := r.message(ctx, message)
		if err != nil {
			return nil, err
		}
		out = append(out, mapped)
	}
	return out, nil
}

// MyInbox is the resolver for the myInbox field.
func (r *queryResolver) MyInbox(ctx context.Context) ([]*model.User, error) {
	current, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	users, err := r.Queries.ListInboxUsers(ctx, current.ID)
	if err != nil {
		return nil, err
	}
	if len(users) > defaultListLimit {
		users = users[:defaultListLimit]
	}
	out := make([]*model.User, 0, len(users))
	for _, user := range users {
		mapped, err := r.user(ctx, user)
		if err != nil {
			return nil, err
		}
		out = append(out, mapped)
	}
	return out, nil
}

// MyNotifications is the resolver for the myNotifications field.
func (r *queryResolver) MyNotifications(ctx context.Context) ([]*model.Notification, error) {
	current, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	notifications, err := r.Queries.ListNotifications(ctx, current.ID)
	if err != nil {
		return nil, err
	}
	if len(notifications) > defaultListLimit {
		notifications = notifications[:defaultListLimit]
	}
	out := make([]*model.Notification, 0, len(notifications))
	for _, notification := range notifications {
		out = append(out, notificationModel(notification))
	}
	return out, nil
}

// MyTeamInvitations is the resolver for the myTeamInvitations field.
func (r *queryResolver) MyTeamInvitations(ctx context.Context) ([]*model.TeamInvitation, error) {
	current, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	rows, err := r.Queries.ListTeamInvitationsForUser(ctx, current.ID)
	if err != nil {
		return nil, err
	}
	if len(rows) > defaultListLimit {
		rows = rows[:defaultListLimit]
	}
	out := make([]*model.TeamInvitation, 0, len(rows))
	for _, row := range rows {
		mapped, err := r.teamInvitation(ctx, row)
		if err != nil {
			return nil, err
		}
		out = append(out, mapped)
	}
	return out, nil
}

// MyJoinRequests is the resolver for the myJoinRequests field.
func (r *queryResolver) MyJoinRequests(ctx context.Context, status *model.JoinRequestStatus) ([]*model.TeamJoinRequest, error) {
	current, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if err := r.expireDueWorkflows(ctx, r.Queries); err != nil {
		return nil, err
	}
	var statusText *string
	if status != nil {
		value := string(*status)
		statusText = &value
	}
	rows, err := r.Queries.ListJoinRequestsForUser(ctx, db.ListJoinRequestsForUserParams{UserID: current.ID, Status: text(statusText)})
	if err != nil {
		return nil, err
	}
	if len(rows) > defaultListLimit {
		rows = rows[:defaultListLimit]
	}
	out := make([]*model.TeamJoinRequest, 0, len(rows))
	for _, row := range rows {
		mapped, err := r.joinRequest(ctx, row)
		if err != nil {
			return nil, err
		}
		out = append(out, mapped)
	}
	return out, nil
}

// TeamJoinRequests is the resolver for the teamJoinRequests field.
func (r *queryResolver) TeamJoinRequests(ctx context.Context, teamID string, status *model.JoinRequestStatus) ([]*model.TeamJoinRequest, error) {
	tid, err := uuid(teamID)
	if err != nil {
		return nil, err
	}
	if err := r.requireTeamLead(ctx, tid); err != nil {
		return nil, err
	}
	if err := r.expireDueWorkflows(ctx, r.Queries); err != nil {
		return nil, err
	}
	var statusText *string
	if status != nil {
		value := string(*status)
		statusText = &value
	}
	rows, err := r.Queries.ListJoinRequestsForTeam(ctx, db.ListJoinRequestsForTeamParams{TeamID: tid, Status: text(statusText)})
	if err != nil {
		return nil, err
	}
	if len(rows) > defaultListLimit {
		rows = rows[:defaultListLimit]
	}
	out := make([]*model.TeamJoinRequest, 0, len(rows))
	for _, row := range rows {
		mapped, err := r.joinRequest(ctx, row)
		if err != nil {
			return nil, err
		}
		out = append(out, mapped)
	}
	return out, nil
}

// UniversalDeadline is the resolver for the universalDeadline field.
func (r *queryResolver) UniversalDeadline(ctx context.Context) (*model.Deadline, error) {
	deadline, err := r.Queries.GetUniversalDeadline(ctx)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return r.deadline(ctx, deadline)
}

// AuditLogs is the resolver for the auditLogs field.
func (r *queryResolver) AuditLogs(ctx context.Context, limit *int) ([]*model.AuditLog, error) {
	if _, err := r.requireAdmin(ctx); err != nil {
		return nil, err
	}
	n := int32(100)
	if limit != nil {
		n = int32(*limit)
	}
	rows, err := r.Queries.ListAuditLogs(ctx, n)
	if err != nil {
		return nil, err
	}
	out := make([]*model.AuditLog, 0, len(rows))
	for _, row := range rows {
		var actor *model.User
		if row.ActorUserID.Valid {
			user, err := r.Queries.GetUser(ctx, row.ActorUserID)
			if err == nil {
				actor, _ = r.shallowUser(ctx, user)
			}
		}
		out = append(out, auditLogModel(row, actor))
	}
	return out, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
