package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"sort"

	pgx "github.com/jackc/pgx/v5"
	"github.com/local/quorum/apps/api/internal/auth"
	"github.com/local/quorum/apps/api/internal/db"
	"github.com/local/quorum/apps/api/internal/graph/generated"
	"github.com/local/quorum/apps/api/internal/graph/model"
	"github.com/local/quorum/apps/api/internal/storage"
)

// BootstrapProfile is the resolver for the bootstrapProfile field.
func (r *mutationResolver) BootstrapProfile(ctx context.Context, input model.BootstrapProfileInput) (*model.User, error) {
	if existing, ok := auth.UserFromContext(ctx); ok {
		return r.user(ctx, existing)
	}
	subject, ok := auth.SubjectFromContext(ctx)
	if !ok || subject == "" {
		return nil, errors.New("verified Neon Auth token required")
	}
	user, err := r.Queries.CreateUser(ctx, db.CreateUserParams{
		AuthUserID: subject,
		Username:   input.Username,
		Email:      text(input.Email),
		FullName:   input.FullName,
		Discipline: text(input.Discipline),
		University: text(input.University),
	})
	if err != nil {
		return nil, err
	}
	return r.user(ctx, user)
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input model.UpdateProfileInput) (*model.User, error) {
	current, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	user, err := r.Queries.UpdateProfile(ctx, db.UpdateProfileParams{
		ID:           current.ID,
		FullName:     input.FullName,
		Bio:          text(input.Bio),
		Discipline:   text(input.Discipline),
		University:   text(input.University),
		LinkedinUrl:  text(input.LinkedinURL),
		GithubUrl:    text(input.GithubURL),
		PortfolioUrl: text(input.PortfolioURL),
		ResumeUrl:    text(input.ResumeURL),
		AvatarUrl:    text(input.AvatarURL),
	})
	if err != nil {
		return nil, err
	}
	return r.user(ctx, user)
}

// CreateTeam is the resolver for the createTeam field.
func (r *mutationResolver) CreateTeam(ctx context.Context, input model.CreateTeamInput) (*model.Team, error) {
	current, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	maxSize := 12
	if input.MaxSize != nil {
		maxSize = *input.MaxSize
	}

	tx, err := r.Pool.Begin(ctx)
	if err != nil {
		return nil, err
	}
	defer tx.Rollback(ctx)
	q := r.Queries.WithTx(tx)

	team, err := q.CreateTeam(ctx, db.CreateTeamParams{
		Name:        input.Name,
		Description: text(input.Description),
		Discipline:  text(input.Discipline),
		MaxSize:     int32(maxSize),
		CreatedBy:   current.ID,
	})
	if err != nil {
		return nil, err
	}
	if _, err := q.AddTeamMember(ctx, db.AddTeamMemberParams{TeamID: team.ID, UserID: current.ID, Role: string(model.TeamRoleLead)}); err != nil {
		return nil, err
	}
	if err := tx.Commit(ctx); err != nil {
		return nil, err
	}
	return r.team(ctx, team)
}

// UpdateTeam is the resolver for the updateTeam field.
func (r *mutationResolver) UpdateTeam(ctx context.Context, id string, input model.UpdateTeamInput) (*model.Team, error) {
	teamID, err := uuid(id)
	if err != nil {
		return nil, err
	}
	if err := r.requireTeamLead(ctx, teamID); err != nil {
		return nil, err
	}
	team, err := r.Queries.UpdateTeam(ctx, db.UpdateTeamParams{
		ID:          teamID,
		Name:        input.Name,
		Description: text(input.Description),
		Discipline:  text(input.Discipline),
		MaxSize:     int32(input.MaxSize),
		IsComplete:  input.IsComplete,
	})
	if err != nil {
		return nil, err
	}
	return r.team(ctx, team)
}

// DeleteTeam is the resolver for the deleteTeam field.
func (r *mutationResolver) DeleteTeam(ctx context.Context, id string) (bool, error) {
	teamID, err := uuid(id)
	if err != nil {
		return false, err
	}
	if err := r.requireTeamLead(ctx, teamID); err != nil {
		return false, err
	}
	return true, r.Queries.DeleteTeam(ctx, teamID)
}

// RemoveMember is the resolver for the removeMember field.
func (r *mutationResolver) RemoveMember(ctx context.Context, teamID string, userID string) (bool, error) {
	tid, err := uuid(teamID)
	if err != nil {
		return false, err
	}
	uid, err := uuid(userID)
	if err != nil {
		return false, err
	}
	if err := r.requireTeamLead(ctx, tid); err != nil {
		return false, err
	}
	return true, r.Queries.RemoveTeamMember(ctx, db.RemoveTeamMemberParams{TeamID: tid, UserID: uid})
}

// PromoteMember is the resolver for the promoteMember field.
func (r *mutationResolver) PromoteMember(ctx context.Context, teamID string, userID string, role model.TeamRole) (*model.TeamMembership, error) {
	tid, err := uuid(teamID)
	if err != nil {
		return nil, err
	}
	uid, err := uuid(userID)
	if err != nil {
		return nil, err
	}
	if err := r.requireTeamLead(ctx, tid); err != nil {
		return nil, err
	}
	member, err := r.Queries.PromoteTeamMember(ctx, db.PromoteTeamMemberParams{TeamID: tid, UserID: uid, Role: string(role)})
	if err != nil {
		return nil, err
	}
	return r.teamMembership(ctx, member)
}

// RequestJoin is the resolver for the requestJoin field.
func (r *mutationResolver) RequestJoin(ctx context.Context, teamID string, message *string) (*model.TeamJoinRequest, error) {
	current, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	tid, err := uuid(teamID)
	if err != nil {
		return nil, err
	}
	request, err := r.Queries.CreateJoinRequest(ctx, db.CreateJoinRequestParams{TeamID: tid, UserID: current.ID, Message: text(message)})
	if err != nil {
		return nil, err
	}
	return r.joinRequest(ctx, request)
}

// RespondToJoinRequest is the resolver for the respondToJoinRequest field.
func (r *mutationResolver) RespondToJoinRequest(ctx context.Context, requestID string, accept bool) (bool, error) {
	id, err := uuid(requestID)
	if err != nil {
		return false, err
	}
	request, err := r.Queries.GetJoinRequest(ctx, id)
	if err != nil {
		return false, err
	}
	if err := r.requireTeamLead(ctx, request.TeamID); err != nil {
		return false, err
	}
	status := model.ApplicationStatusRejected
	if accept {
		status = model.ApplicationStatusAccepted
	}
	if _, err := r.Queries.RespondToJoinRequest(ctx, db.RespondToJoinRequestParams{ID: id, Status: string(status)}); err != nil {
		return false, err
	}
	if accept {
		if _, err := r.Queries.AddTeamMember(ctx, db.AddTeamMemberParams{TeamID: request.TeamID, UserID: request.UserID, Role: string(model.TeamRoleMember)}); err != nil {
			return false, err
		}
	}
	return true, nil
}

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input model.CreateProjectInput) (*model.Project, error) {
	current, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	minSize := 10
	if input.TeamSizeMin != nil {
		minSize = *input.TeamSizeMin
	}
	maxSize := 12
	if input.TeamSizeMax != nil {
		maxSize = *input.TeamSizeMax
	}
	project, err := r.Queries.CreateProject(ctx, db.CreateProjectParams{
		Title:       input.Title,
		Description: input.Description,
		Constraints: text(input.Constraints),
		Disciplines: input.Disciplines,
		TeamSizeMin: int32(minSize),
		TeamSizeMax: int32(maxSize),
		OwnerID:     current.ID,
		FileUrl:     text(input.FileURL),
		VideoUrl:    text(input.VideoURL),
	})
	if err != nil {
		return nil, err
	}
	return r.project(ctx, project)
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationResolver) UpdateProject(ctx context.Context, id string, input model.UpdateProjectInput) (*model.Project, error) {
	projectID, err := uuid(id)
	if err != nil {
		return nil, err
	}
	if err := r.requireProjectOwner(ctx, projectID); err != nil {
		return nil, err
	}
	project, err := r.Queries.UpdateProject(ctx, db.UpdateProjectParams{
		ID:          projectID,
		Title:       input.Title,
		Description: input.Description,
		Constraints: text(input.Constraints),
		Disciplines: input.Disciplines,
		TeamSizeMin: int32(input.TeamSizeMin),
		TeamSizeMax: int32(input.TeamSizeMax),
		Status:      string(input.Status),
		FileUrl:     text(input.FileURL),
		VideoUrl:    text(input.VideoURL),
	})
	if err != nil {
		return nil, err
	}
	return r.project(ctx, project)
}

// DeleteProject is the resolver for the deleteProject field.
func (r *mutationResolver) DeleteProject(ctx context.Context, id string) (bool, error) {
	projectID, err := uuid(id)
	if err != nil {
		return false, err
	}
	if err := r.requireProjectOwner(ctx, projectID); err != nil {
		return false, err
	}
	return true, r.Queries.DeleteProject(ctx, projectID)
}

// ApplyToProject is the resolver for the applyToProject field.
func (r *mutationResolver) ApplyToProject(ctx context.Context, projectID string, teamID string, message *string) (*model.ProjectApplication, error) {
	tid, err := uuid(teamID)
	if err != nil {
		return nil, err
	}
	pid, err := uuid(projectID)
	if err != nil {
		return nil, err
	}
	if err := r.requireTeamLead(ctx, tid); err != nil {
		return nil, err
	}
	application, err := r.Queries.ApplyToProject(ctx, db.ApplyToProjectParams{ProjectID: pid, TeamID: tid, Message: text(message)})
	if err != nil {
		return nil, err
	}
	return r.projectApplication(ctx, application)
}

// RespondToApplication is the resolver for the respondToApplication field.
func (r *mutationResolver) RespondToApplication(ctx context.Context, applicationID string, accept bool) (bool, error) {
	id, err := uuid(applicationID)
	if err != nil {
		return false, err
	}
	application, err := r.Queries.GetProjectApplication(ctx, id)
	if err != nil {
		return false, err
	}
	if err := r.requireProjectOwner(ctx, application.ProjectID); err != nil {
		return false, err
	}
	status := model.ApplicationStatusRejected
	if accept {
		status = model.ApplicationStatusAccepted
	}
	if _, err := r.Queries.RespondToApplication(ctx, db.RespondToApplicationParams{ID: id, Status: string(status)}); err != nil {
		return false, err
	}
	if accept {
		if _, err := r.Queries.ClaimProject(ctx, db.ClaimProjectParams{ID: application.ProjectID, TeamID: application.TeamID}); err != nil {
			return false, err
		}
	}
	return true, nil
}

// AssociateProject is the resolver for the associateProject field.
func (r *mutationResolver) AssociateProject(ctx context.Context, teamID string, projectID string) (*model.Team, error) {
	tid, err := uuid(teamID)
	if err != nil {
		return nil, err
	}
	pid, err := uuid(projectID)
	if err != nil {
		return nil, err
	}
	if err := r.requireTeamLead(ctx, tid); err != nil {
		return nil, err
	}
	team, err := r.Queries.AssociateProject(ctx, db.AssociateProjectParams{ID: tid, ProjectID: pid})
	if err != nil {
		return nil, err
	}
	return r.team(ctx, team)
}

// SendMessage is the resolver for the sendMessage field.
func (r *mutationResolver) SendMessage(ctx context.Context, receiverID string, body string) (*model.Message, error) {
	current, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	rid, err := uuid(receiverID)
	if err != nil {
		return nil, err
	}
	message, err := r.Queries.SendMessage(ctx, db.SendMessageParams{SenderID: current.ID, ReceiverID: rid, Body: body})
	if err != nil {
		return nil, err
	}
	return r.message(ctx, message)
}

// MarkRead is the resolver for the markRead field.
func (r *mutationResolver) MarkRead(ctx context.Context, messageID string) (bool, error) {
	current, err := requireUser(ctx)
	if err != nil {
		return false, err
	}
	id, err := uuid(messageID)
	if err != nil {
		return false, err
	}
	message, err := r.Queries.GetMessage(ctx, id)
	if err != nil {
		return false, err
	}
	if !sameUUID(message.ReceiverID, current.ID) {
		return false, errors.New("not authorized")
	}
	_, err = r.Queries.MarkMessageRead(ctx, id)
	return err == nil, err
}

// MarkNotificationRead is the resolver for the markNotificationRead field.
func (r *mutationResolver) MarkNotificationRead(ctx context.Context, notificationID string) (bool, error) {
	current, err := requireUser(ctx)
	if err != nil {
		return false, err
	}
	id, err := uuid(notificationID)
	if err != nil {
		return false, err
	}
	notification, err := r.Queries.GetNotification(ctx, id)
	if err != nil {
		return false, err
	}
	if !sameUUID(notification.UserID, current.ID) {
		return false, errors.New("not authorized")
	}
	_, err = r.Queries.MarkNotificationRead(ctx, id)
	return err == nil, err
}

// SignUpload is the resolver for the signUpload field.
func (r *mutationResolver) SignUpload(ctx context.Context, input model.SignUploadInput) (*model.UploadSignature, error) {
	current, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	if r.Storage == nil {
		return nil, errors.New("storage signing is not configured")
	}
	post, err := r.Storage.PresignPost(ctx, storage.AssetKind(input.Kind), uuidString(current.ID), input.Filename, input.ContentType, int64(input.Size))
	if err != nil {
		return nil, err
	}
	fields := make([]*model.UploadField, 0, len(post.Fields))
	names := make([]string, 0, len(post.Fields))
	for name := range post.Fields {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		fields = append(fields, &model.UploadField{Name: name, Value: post.Fields[name]})
	}
	var publicURL *string
	if post.PublicURL != "" {
		publicURL = &post.PublicURL
	}
	return &model.UploadSignature{
		URL:       post.URL,
		Key:       post.Key,
		PublicURL: publicURL,
		ExpiresAt: post.ExpiresAt.UTC().Format("2006-01-02T15:04:05Z07:00"),
		Fields:    fields,
	}, nil
}

// RemoveUser is the resolver for the removeUser field.
func (r *mutationResolver) RemoveUser(ctx context.Context, userID string) (bool, error) {
	current, err := requireUser(ctx)
	if err != nil {
		return false, err
	}
	isAdmin, err := r.Queries.IsAdmin(ctx, current.ID)
	if err != nil {
		return false, err
	}
	if !isAdmin {
		return false, errors.New("admin access required")
	}
	id, err := uuid(userID)
	if err != nil {
		return false, err
	}
	return true, r.Queries.DeleteUser(ctx, id)
}

// RemoveTeam is the resolver for the removeTeam field.
func (r *mutationResolver) RemoveTeam(ctx context.Context, teamID string) (bool, error) {
	current, err := requireUser(ctx)
	if err != nil {
		return false, err
	}
	isAdmin, err := r.Queries.IsAdmin(ctx, current.ID)
	if err != nil {
		return false, err
	}
	if !isAdmin {
		return false, errors.New("admin access required")
	}
	id, err := uuid(teamID)
	if err != nil {
		return false, err
	}
	return true, r.Queries.DeleteTeam(ctx, id)
}

// RemoveProject is the resolver for the removeProject field.
func (r *mutationResolver) RemoveProject(ctx context.Context, projectID string) (bool, error) {
	current, err := requireUser(ctx)
	if err != nil {
		return false, err
	}
	isAdmin, err := r.Queries.IsAdmin(ctx, current.ID)
	if err != nil {
		return false, err
	}
	if !isAdmin {
		return false, errors.New("admin access required")
	}
	id, err := uuid(projectID)
	if err != nil {
		return false, err
	}
	return true, r.Queries.DeleteProject(ctx, id)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	current, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	return r.user(ctx, current)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, username string) (*model.User, error) {
	user, err := r.Queries.GetUserByUsername(ctx, username)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return r.user(ctx, user)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, discipline *string, tag *string, search *string) ([]*model.User, error) {
	users, err := r.Queries.ListUsers(ctx, db.ListUsersParams{Discipline: text(discipline), Tag: text(tag), Search: text(search)})
	if err != nil {
		return nil, err
	}
	out := make([]*model.User, 0, len(users))
	for _, user := range users {
		mapped, err := r.user(ctx, user)
		if err != nil {
			return nil, err
		}
		out = append(out, mapped)
	}
	return out, nil
}

// Team is the resolver for the team field.
func (r *queryResolver) Team(ctx context.Context, id string) (*model.Team, error) {
	teamID, err := uuid(id)
	if err != nil {
		return nil, err
	}
	team, err := r.Queries.GetTeam(ctx, teamID)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return r.team(ctx, team)
}

// Teams is the resolver for the teams field.
func (r *queryResolver) Teams(ctx context.Context, discipline *string, hasProject *bool, isComplete *bool, search *string) ([]*model.Team, error) {
	teams, err := r.Queries.ListTeams(ctx, db.ListTeamsParams{
		Discipline: text(discipline),
		HasProject: boolValue(hasProject),
		IsComplete: boolValue(isComplete),
		Search:     text(search),
	})
	if err != nil {
		return nil, err
	}
	out := make([]*model.Team, 0, len(teams))
	for _, team := range teams {
		mapped, err := r.team(ctx, team)
		if err != nil {
			return nil, err
		}
		out = append(out, mapped)
	}
	return out, nil
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id string) (*model.Project, error) {
	projectID, err := uuid(id)
	if err != nil {
		return nil, err
	}
	project, err := r.Queries.GetProject(ctx, projectID)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return r.project(ctx, project)
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context, discipline *string, status *model.ProjectStatus, search *string) ([]*model.Project, error) {
	var statusText *string
	if status != nil {
		value := string(*status)
		statusText = &value
	}
	projects, err := r.Queries.ListProjects(ctx, db.ListProjectsParams{Discipline: text(discipline), Status: text(statusText), Search: text(search)})
	if err != nil {
		return nil, err
	}
	out := make([]*model.Project, 0, len(projects))
	for _, project := range projects {
		mapped, err := r.project(ctx, project)
		if err != nil {
			return nil, err
		}
		out = append(out, mapped)
	}
	return out, nil
}

// MyMessages is the resolver for the myMessages field.
func (r *queryResolver) MyMessages(ctx context.Context, withUser string) ([]*model.Message, error) {
	current, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	otherID, err := uuid(withUser)
	if err != nil {
		return nil, err
	}
	messages, err := r.Queries.ListMessagesWithUser(ctx, db.ListMessagesWithUserParams{SenderID: current.ID, ReceiverID: otherID})
	if err != nil {
		return nil, err
	}
	out := make([]*model.Message, 0, len(messages))
	for _, message := range messages {
		mapped, err := r.message(ctx, message)
		if err != nil {
			return nil, err
		}
		out = append(out, mapped)
	}
	return out, nil
}

// MyInbox is the resolver for the myInbox field.
func (r *queryResolver) MyInbox(ctx context.Context) ([]*model.User, error) {
	current, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	users, err := r.Queries.ListInboxUsers(ctx, current.ID)
	if err != nil {
		return nil, err
	}
	out := make([]*model.User, 0, len(users))
	for _, user := range users {
		mapped, err := r.user(ctx, user)
		if err != nil {
			return nil, err
		}
		out = append(out, mapped)
	}
	return out, nil
}

// MyNotifications is the resolver for the myNotifications field.
func (r *queryResolver) MyNotifications(ctx context.Context) ([]*model.Notification, error) {
	current, err := requireUser(ctx)
	if err != nil {
		return nil, err
	}
	notifications, err := r.Queries.ListNotifications(ctx, current.ID)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Notification, 0, len(notifications))
	for _, notification := range notifications {
		out = append(out, notificationModel(notification))
	}
	return out, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
